import * as React from 'react'
import { useQuery } from '@tanstack/react-query'
import { Boxes, KeyRound, MonitorSmartphone, ShieldCheck, UserRound } from 'lucide-react'
import { Badge } from '@/components/ui/badge'
import { Input, Textarea } from '@/components/ui/input'
import { Field } from '@/components/ui/label'
import { MultiCombobox } from '@/components/ui/multi-combobox'
import type { ComboOption } from '@/components/ui/combobox'
import { Select } from '@/components/ui/select'
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs'
import { describeSignInRule } from '@/features/runs/plan-model'
import { tierOf, type Tier } from '@/lib/tier'
import { authPolicyTierIssues, authSiloTierIssues, authTier, deviceSyncTierIssues } from '@/lib/tier-rules'
import { ListEditor, type FormProps, type Item } from './list-editor'
import { FormSection, SwitchRow, setField, useOuOptions } from './form-helpers'
import { PrincipalCombobox, PrincipalMultiCombobox } from './lookups'
import { useSectionContent } from './draft-store'
import { sectionQuery } from './queries'
import { useGroupTierMap } from './tier-rule-alerts'
import type { EditorProps } from './editors'

/* Authentication policies, authentication policy silos and device group synchronisation
 * (tiermodel-authsilos.json). The SDDL is generated by the framework; the form only shows the rule in words. */

export const TGT_MIN = 45
export const TGT_MAX = 600
const NONE = '__none'
const AUTO = 'auto'

/** "OU=Tier 0 Accounts,OU=Tier 0,OU=Admin,{{DOMAIN_DN}}" → "Admin › Tier 0 › Tier 0 Accounts" */
export function ouLabel(dn: string): string {
  const rel = dn.replace(/,?\{\{DOMAIN_DN\}\}$/i, '')
  if (!rel) return 'Domänenstamm'
  return rel
    .split(/,(?=\s*[A-Za-z]+=)/)
    .map((p) => p.trim().replace(/^[A-Za-z]+=/, ''))
    .reverse()
    .join(' › ')
}

const lastRdn = (dn: string) => ouLabel(dn).split(' › ').pop() ?? dn

const strings = (v: unknown): string[] => (Array.isArray(v) ? v.filter((x): x is string => typeof x === 'string' && !!x) : [])

function itemTier(o: Item): Tier {
  const t = authTier(o)
  return t === 0 || t === 1 || t === 2 ? t : tierOf(o.name ?? o.group)
}

function ModeBadge({ enforce }: { enforce: unknown }) {
  return enforce ? <Badge variant="danger">Erzwungen</Badge> : <Badge variant="info">Überwachung</Badge>
}

function RulePreview({ title = 'Wirkung', children }: { title?: string; children: React.ReactNode }) {
  return (
    <div className="rounded-lg border border-dashed bg-muted/30 px-3.5 py-3" aria-live="polite">
      <p className="text-[11px] font-medium tracking-wide text-muted-foreground uppercase">{title}</p>
      <div className="mt-1 text-[13px] leading-relaxed">{children}</div>
    </div>
  )
}

function TierSelect({ value, onChange, id }: { value: Item; onChange: (v: Item) => void; id: string }) {
  return (
    <Field label="Tier" htmlFor={id} hint="Für die Einstufung im Audit. „Automatisch“ erkennt das Tier am Namen.">
      <Select
        id={id}
        value={value.tier === 0 || value.tier === 1 || value.tier === 2 ? String(value.tier) : AUTO}
        onValueChange={(v) => onChange(setField(value, 'tier', v === AUTO ? undefined : Number(v), true))}
        options={[
          { value: AUTO, label: 'Automatisch (aus dem Namen)' },
          { value: '0', label: 'Tier 0' },
          { value: '1', label: 'Tier 1' },
          { value: '2', label: 'Tier 2' },
        ]}
      />
    </Field>
  )
}

function CommentField({ value, onChange, id }: { value: Item; onChange: (v: Item) => void; id: string }) {
  return (
    <Field label="Kommentar" htmlFor={id}>
      <Textarea id={id} rows={2} value={value.comment ?? ''} onChange={(e) => onChange(setField(value, 'comment', e.target.value, !('comment' in value)))} />
    </Field>
  )
}

/** Sentence for a policy's sign-in rule. */
export function policyRuleText(p: Item | undefined): string {
  const from = (p?.allowedToAuthenticateFrom ?? {}) as Item
  return describeSignInRule(!!from.includeDomainControllers, strings(from.deviceGroups))
}

function useAuthContent() {
  useQuery(sectionQuery('authsilos'))
  return useSectionContent('authsilos') as Item | undefined
}

// ============================================================ policies

function PolicyForm({ value, onChange, errors }: FormProps) {
  const from = (value.allowedToAuthenticateFrom ?? {}) as Item
  const setFrom = (key: string, v: unknown) => onChange({ ...value, allowedToAuthenticateFrom: { ...from, [key]: v } })
  const tgt = value.userTgtLifetimeMins
  return (
    <>
      <FormSection title="Allgemein">
        <Field label="Name" htmlFor="ap-name" required error={errors.name}>
          <Input id="ap-name" value={value.name ?? ''} onChange={(e) => onChange(setField(value, 'name', e.target.value))} aria-invalid={!!errors.name} placeholder="z. B. Tier 0 Authentication Policy" />
        </Field>
        <Field label="Beschreibung" htmlFor="ap-desc">
          <Textarea id="ap-desc" rows={2} value={value.description ?? ''} onChange={(e) => onChange(setField(value, 'description', e.target.value))} />
        </Field>
        <SwitchRow
          id="ap-enforce"
          label="Erzwingen"
          description={value.enforce ? 'Anmeldungen, die gegen die Richtlinie verstoßen, werden blockiert.' : 'Überwachungsmodus: Verstöße werden nur protokolliert, nichts wird blockiert.'}
          checked={!!value.enforce}
          onCheckedChange={(v) => onChange(setField(value, 'enforce', v))}
        />
        <Field
          label="TGT-Lebensdauer (Minuten)"
          htmlFor="ap-tgt"
          error={errors.userTgtLifetimeMins}
          hint={`${TGT_MIN} bis ${TGT_MAX} Minuten. Protected Users verwenden 240 Minuten; leer lassen, um den Wert im AD nicht zu ändern.`}
        >
          <Input
            id="ap-tgt"
            type="number"
            inputMode="numeric"
            className="max-w-40"
            value={tgt === null || tgt === undefined ? '' : String(tgt)}
            onChange={(e) => onChange(setField(value, 'userTgtLifetimeMins', e.target.value === '' ? null : Number(e.target.value)))}
            aria-invalid={!!errors.userTgtLifetimeMins}
          />
        </Field>
      </FormSection>
      <FormSection title="Anmeldung erlaubt von" description="Die Bedingung gilt für das Gerät, an dem sich ein Konto anmeldet.">
        <SwitchRow
          id="ap-dcs"
          label="Domänencontroller"
          description="Anmeldung an jedem Domänencontroller der Gesamtstruktur."
          checked={!!from.includeDomainControllers}
          onCheckedChange={(v) => setFrom('includeDomainControllers', v)}
        />
        <Field label="Gerätegruppen" htmlFor="ap-groups" error={errors.deviceGroups} hint="Anmeldung von Computern, die Mitglied mindestens einer dieser Gruppen sind.">
          <PrincipalMultiCombobox id="ap-groups" values={strings(from.deviceGroups)} onChange={(v) => setFrom('deviceGroups', v)} placeholder="Computergruppe suchen und hinzufügen …" />
        </Field>
        <RulePreview>{policyRuleText(value)}</RulePreview>
      </FormSection>
      <TierSelect value={value} onChange={onChange} id="ap-tier" />
      <CommentField value={value} onChange={onChange} id="ap-comment" />
    </>
  )
}

function PoliciesList({ items, onItemsChange, readOnly }: { items: Item[]; onItemsChange: (n: Item[], tag?: string) => void; readOnly: boolean }) {
  const groupTiers = useGroupTierMap()
  return (
    <ListEditor
      items={items}
      onItemsChange={onItemsChange}
      hints={(p) => authPolicyTierIssues(p, groupTiers)}
      columns={[
        { id: 'name', header: 'Name', cell: (p) => <span className="block min-w-[120px] font-medium">{p.name}</span>, sortValue: (p) => p.name ?? '' },
        { id: 'mode', header: 'Modus', cell: (p) => <ModeBadge enforce={p.enforce} />, sortValue: (p) => (p.enforce ? 1 : 0) },
        {
          id: 'rule', header: 'Anmeldung',
          cell: (p) => <span className="line-clamp-2 min-w-[180px] max-w-md text-muted-foreground">{policyRuleText(p)}</span>,
          className: 'hidden @2xl:table-cell',
        },
        {
          id: 'tgt', header: 'TGT', cell: (p) => (typeof p.userTgtLifetimeMins === 'number' ? `${p.userTgtLifetimeMins} min` : <span className="text-muted-foreground">unverändert</span>),
          sortValue: (p) => p.userTgtLifetimeMins ?? 0, className: 'hidden @4xl:table-cell',
        },
      ]}
      searchText={(p) => `${p.name} ${p.description ?? ''} ${strings(p.allowedToAuthenticateFrom?.deviceGroups).join(' ')} ${p.comment ?? ''}`}
      tierOf={itemTier}
      itemLabel={(p) => p.name}
      newItem={() => ({ name: '', description: '', enforce: false, userTgtLifetimeMins: 240, allowedToAuthenticateFrom: { includeDomainControllers: false, deviceGroups: [] }, comment: '' })}
      Form={PolicyForm}
      entity={{ singular: 'Richtlinie', plural: 'Richtlinien', article: 'die' }}
      readOnly={readOnly}
      defaultSort="name"
      validate={(p, all, index) => validatePolicy(p, all, index)}
    />
  )
}

export function validatePolicy(p: Item, all: Item[], index: number | null): Record<string, string> {
  const e: Record<string, string> = {}
  const name = String(p.name ?? '').trim()
  if (!name) e.name = 'Name ist erforderlich.'
  else if (all.some((x, i) => i !== index && String(x.name ?? '').trim().toLowerCase() === name.toLowerCase())) e.name = 'Eine Richtlinie mit diesem Namen existiert bereits.'
  const tgt = p.userTgtLifetimeMins
  if (tgt !== null && tgt !== undefined && (!Number.isInteger(tgt) || tgt < TGT_MIN || tgt > TGT_MAX))
    e.userTgtLifetimeMins = `Bitte eine ganze Zahl von ${TGT_MIN} bis ${TGT_MAX} angeben oder leer lassen.`
  return e
}

// ============================================================ silos

function usePolicyOptions() {
  const content = useAuthContent()
  const policies = strings((content?.authenticationPolicies ?? []).map((p: Item) => p.name))
  return [{ value: NONE, label: 'Keine' }, ...policies.map((n) => ({ value: n, label: n }))]
}

function useAccountOptions(): ComboOption[] {
  useQuery(sectionQuery('users'))
  const users = useSectionContent('users') as Item | undefined
  return React.useMemo(
    () =>
      ((users?.users ?? []) as Item[])
        .filter((u) => u.samAccountName)
        .map((u) => ({ value: String(u.samAccountName), label: String(u.samAccountName), hint: u.displayName || u.ouPath, icon: <UserRound className="size-4 text-muted-foreground" /> })),
    [users],
  )
}

function SiloForm({ value, onChange, errors }: FormProps) {
  const policyOptions = usePolicyOptions()
  const ouOptions = useOuOptions()
  const accountOptions = useAccountOptions()
  const content = useAuthContent()
  const members = (value.members ?? {}) as Item
  const setMembers = (key: string, v: string[]) => onChange({ ...value, members: { ...members, [key]: v } })
  const policy = (field: string) => (
    <Select
      id={`as-${field}`}
      value={value[field] ? String(value[field]) : NONE}
      onValueChange={(v) => onChange(setField(value, field, v === NONE ? '' : v))}
      options={policyOptions.some((o) => o.value === value[field]) || !value[field] ? policyOptions : [...policyOptions, { value: String(value[field]), label: `${value[field]} (nicht konfiguriert)` }]}
    />
  )
  const userPolicy = (content?.authenticationPolicies ?? []).find((p: Item) => p.name === value.userAuthenticationPolicy) as Item | undefined
  const userOus = strings(members.userOUs)
  const computerOus = strings(members.computerOUs)
  const computerGroups = strings(members.computerGroups)
  const excluded = strings(members.excludeAccounts)

  return (
    <>
      <FormSection title="Allgemein">
        <Field label="Name" htmlFor="as-name" required error={errors.name}>
          <Input id="as-name" value={value.name ?? ''} onChange={(e) => onChange(setField(value, 'name', e.target.value))} aria-invalid={!!errors.name} placeholder="z. B. Tier 0 Authentication Silo" />
        </Field>
        <Field label="Beschreibung" htmlFor="as-desc">
          <Textarea id="as-desc" rows={2} value={value.description ?? ''} onChange={(e) => onChange(setField(value, 'description', e.target.value))} />
        </Field>
        <SwitchRow
          id="as-enforce"
          label="Erzwingen"
          description={value.enforce ? 'Die Richtlinien des Silos werden für seine Mitglieder durchgesetzt.' : 'Überwachungsmodus: Verstöße werden nur protokolliert.'}
          checked={!!value.enforce}
          onCheckedChange={(v) => onChange(setField(value, 'enforce', v))}
        />
      </FormSection>
      <FormSection title="Richtlinien" description="Aus den konfigurierten Authentifizierungsrichtlinien">
        <Field label="Für Benutzerkonten" htmlFor="as-userAuthenticationPolicy" error={errors.userAuthenticationPolicy}>{policy('userAuthenticationPolicy')}</Field>
        <div className="grid gap-4 sm:grid-cols-2">
          <Field label="Für Computerkonten" htmlFor="as-computerAuthenticationPolicy" error={errors.computerAuthenticationPolicy}>{policy('computerAuthenticationPolicy')}</Field>
          <Field label="Für Dienstkonten (MSA)" htmlFor="as-serviceAuthenticationPolicy" error={errors.serviceAuthenticationPolicy}>{policy('serviceAuthenticationPolicy')}</Field>
        </div>
      </FormSection>
      <FormSection title="Mitglieder" description="Konten werden im Silo zugelassen und ihm zugewiesen.">
        <Field label="Benutzer-OUs" htmlFor="as-userous" hint="Alle Benutzer unterhalb dieser OUs (mit Unterordnern).">
          <MultiCombobox id="as-userous" values={userOus} onChange={(v) => setMembers('userOUs', v)} options={ouOptions} placeholder="OU suchen und hinzufügen …" allowCustom={false} />
        </Field>
        <Field label="Computer-OUs" htmlFor="as-compous" hint="Alle Computer unterhalb dieser OUs.">
          <MultiCombobox id="as-compous" values={computerOus} onChange={(v) => setMembers('computerOUs', v)} options={ouOptions} placeholder="OU suchen und hinzufügen …" allowCustom={false} />
        </Field>
        <Field label="Computergruppen" htmlFor="as-compgroups" hint="Computer, die direkte Mitglieder dieser Gruppen sind.">
          <PrincipalMultiCombobox id="as-compgroups" values={computerGroups} onChange={(v) => setMembers('computerGroups', v)} placeholder="Gruppe suchen und hinzufügen …" />
        </Field>
        <Field label="Ausgenommene Konten" htmlFor="as-exclude" hint="sAMAccountName – werden nie aufgenommen (z. B. ein Notfallkonto). Freie Eingabe möglich.">
          <MultiCombobox id="as-exclude" values={excluded} onChange={(v) => setMembers('excludeAccounts', v)} options={accountOptions} placeholder="Konto suchen oder eingeben …" />
        </Field>
        <RulePreview>
          <SiloSentence silo={value} userPolicy={userPolicy} />
        </RulePreview>
      </FormSection>
      <TierSelect value={value} onChange={onChange} id="as-tier" />
      <CommentField value={value} onChange={onChange} id="as-comment" />
    </>
  )
}

function SiloSentence({ silo, userPolicy }: { silo: Item; userPolicy: Item | undefined }) {
  const m = (silo.members ?? {}) as Item
  const who: string[] = []
  const userOus = strings(m.userOUs)
  const computerOus = strings(m.computerOUs)
  const groups = strings(m.computerGroups)
  if (userOus.length) who.push(`alle Benutzer unter ${userOus.map(lastRdn).join(', ')}`)
  if (computerOus.length) who.push(`alle Computer unter ${computerOus.map(lastRdn).join(', ')}`)
  if (groups.length) who.push(`die Computer der Gruppe${groups.length > 1 ? 'n' : ''} ${groups.join(', ')}`)
  const excluded = strings(m.excludeAccounts)
  return (
    <>
      {who.length ? (
        <p>
          Aufgenommen werden {who.join(', ')}
          {excluded.length ? `, außer ${excluded.join(', ')}` : ''}.
        </p>
      ) : (
        <p className="text-muted-foreground">Noch keine Mitglieder festgelegt.</p>
      )}
      <p className="mt-1">
        {silo.userAuthenticationPolicy ? (
          <>Für ihre Benutzerkonten gilt: {policyRuleText(userPolicy)}{userPolicy ? '.' : ' (Richtlinie ist nicht konfiguriert).'}</>
        ) : (
          <span className="text-muted-foreground">Ohne Benutzerrichtlinie schränkt das Silo die Anmeldung nicht ein.</span>
        )}
      </p>
      <p className="mt-1 text-muted-foreground">{silo.enforce ? 'Das Silo wird erzwungen.' : 'Das Silo läuft im Überwachungsmodus.'}</p>
    </>
  )
}

function SilosList({ items, onItemsChange, readOnly, policies }: { items: Item[]; onItemsChange: (n: Item[], tag?: string) => void; readOnly: boolean; policies: Item[] }) {
  const groupTiers = useGroupTierMap()
  return (
    <ListEditor
      items={items}
      onItemsChange={onItemsChange}
      hints={(s) => authSiloTierIssues(s, policies, groupTiers)}
      columns={[
        { id: 'name', header: 'Name', cell: (s) => <span className="block min-w-[120px] font-medium">{s.name}</span>, sortValue: (s) => s.name ?? '' },
        { id: 'mode', header: 'Modus', cell: (s) => <ModeBadge enforce={s.enforce} />, sortValue: (s) => (s.enforce ? 1 : 0) },
        { id: 'policy', header: 'Benutzerrichtlinie', cell: (s) => s.userAuthenticationPolicy || <span className="text-muted-foreground">–</span>, sortValue: (s) => s.userAuthenticationPolicy ?? '', className: 'hidden @2xl:table-cell' },
        {
          id: 'members', header: 'Mitglieder',
          cell: (s) => {
            const m = (s.members ?? {}) as Item
            const parts = [...strings(m.userOUs), ...strings(m.computerOUs)].map(lastRdn).concat(strings(m.computerGroups))
            return <span className="line-clamp-2 max-w-sm text-muted-foreground">{parts.join(', ') || '–'}</span>
          },
          className: 'hidden @4xl:table-cell',
        },
      ]}
      searchText={(s) => `${s.name} ${s.description ?? ''} ${s.userAuthenticationPolicy ?? ''} ${JSON.stringify(s.members ?? {})}`}
      tierOf={itemTier}
      itemLabel={(s) => s.name}
      newItem={() => ({
        name: '', description: '', enforce: false, userAuthenticationPolicy: '', computerAuthenticationPolicy: '', serviceAuthenticationPolicy: '',
        members: { userOUs: [], computerGroups: [], computerOUs: [], excludeAccounts: [] }, comment: '',
      })}
      Form={SiloForm}
      entity={{ singular: 'Silo', plural: 'Silos', article: 'das' }}
      readOnly={readOnly}
      defaultSort="name"
      validate={(s, all, index) => validateSilo(s, all, index, policies)}
    />
  )
}

export function validateSilo(s: Item, all: Item[], index: number | null, policies: Item[]): Record<string, string> {
  const e: Record<string, string> = {}
  const name = String(s.name ?? '').trim()
  if (!name) e.name = 'Name ist erforderlich.'
  else if (all.some((x, i) => i !== index && String(x.name ?? '').trim().toLowerCase() === name.toLowerCase())) e.name = 'Ein Silo mit diesem Namen existiert bereits.'
  const known = new Set(policies.map((p) => String(p.name ?? '').toLowerCase()))
  for (const field of ['userAuthenticationPolicy', 'computerAuthenticationPolicy', 'serviceAuthenticationPolicy'])
    if (s[field] && !known.has(String(s[field]).toLowerCase())) e[field] = 'Diese Richtlinie ist nicht konfiguriert.'
  return e
}

// ============================================================ device group sync

function SyncForm({ value, onChange, errors }: FormProps) {
  const ouOptions = useOuOptions()
  const sources = strings(value.sourceOUs)
  return (
    <>
      <FormSection title="Gerätegruppe">
        <Field label="Gruppe" htmlFor="ds-group" required error={errors.group} hint="sAMAccountName der Computergruppe, die gefüllt wird.">
          <PrincipalCombobox id="ds-group" value={value.group ?? ''} onChange={(v) => onChange(setField(value, 'group', v))} placeholder="Gruppe wählen" invalid={!!errors.group} />
        </Field>
        <Field label="Quell-OUs" htmlFor="ds-ous" required error={errors.sourceOUs} hint="Alle Computer unterhalb dieser OUs werden der Gruppe hinzugefügt – nie entfernt.">
          <MultiCombobox id="ds-ous" values={sources} onChange={(v) => onChange(setField(value, 'sourceOUs', v))} options={ouOptions} placeholder="OU suchen und hinzufügen …" allowCustom={false} invalid={!!errors.sourceOUs} />
        </Field>
        <RulePreview>
          {value.group && sources.length ? (
            <p>Alle Computer unter {sources.map(lastRdn).join(', ')} werden Mitglied von {value.group}.</p>
          ) : (
            <p className="text-muted-foreground">Gruppe und mindestens eine Quell-OU wählen.</p>
          )}
        </RulePreview>
      </FormSection>
      <TierSelect value={value} onChange={onChange} id="ds-tier" />
      <CommentField value={value} onChange={onChange} id="ds-comment" />
    </>
  )
}

function SyncList({ items, onItemsChange, readOnly }: { items: Item[]; onItemsChange: (n: Item[], tag?: string) => void; readOnly: boolean }) {
  const groupTiers = useGroupTierMap()
  return (
    <ListEditor
      items={items}
      onItemsChange={onItemsChange}
      hints={(d) => deviceSyncTierIssues(d, groupTiers)}
      columns={[
        { id: 'group', header: 'Gerätegruppe', cell: (d) => <span className="font-medium">{d.group}</span>, sortValue: (d) => d.group ?? '' },
        {
          id: 'sources', header: 'Quell-OUs',
          cell: (d) => <span className="line-clamp-2 max-w-md text-muted-foreground">{strings(d.sourceOUs).map(ouLabel).join('; ') || '–'}</span>,
        },
      ]}
      searchText={(d) => `${d.group} ${strings(d.sourceOUs).join(' ')} ${d.comment ?? ''}`}
      tierOf={(d) => (d.tier === 0 || d.tier === 1 || d.tier === 2 ? d.tier : tierOf(d.group))}
      itemLabel={(d) => d.group}
      newItem={() => ({ group: '', sourceOUs: [], comment: '' })}
      Form={SyncForm}
      entity={{ singular: 'Synchronisierung', plural: 'Synchronisierungen', article: 'die' }}
      readOnly={readOnly}
      defaultSort="group"
      validate={(d, all, index) => validateSync(d, all, index)}
    />
  )
}

export function validateSync(d: Item, all: Item[], index: number | null): Record<string, string> {
  const e: Record<string, string> = {}
  const group = String(d.group ?? '').trim()
  if (!group) e.group = 'Gruppe ist erforderlich.'
  else if (all.some((x, i) => i !== index && String(x.group ?? '').trim().toLowerCase() === group.toLowerCase())) e.group = 'Für diese Gruppe gibt es bereits eine Synchronisierung.'
  if (!strings(d.sourceOUs).length) e.sourceOUs = 'Mindestens eine Quell-OU wählen.'
  return e
}

// ============================================================ section editor

type TabKey = 'policies' | 'silos' | 'sync'

export function AuthSilosEditor(props: EditorProps) {
  const content = (props.content ?? {}) as Item
  const policies: Item[] = Array.isArray(content.authenticationPolicies) ? content.authenticationPolicies : []
  const silos: Item[] = Array.isArray(content.authenticationPolicySilos) ? content.authenticationPolicySilos : []
  const sync: Item[] = Array.isArray(content.deviceGroupSync) ? content.deviceGroupSync : []
  const [tab, setTab] = React.useState<TabKey>('policies')
  const bind = (listKey: string) => (next: Item[], tag?: string) => props.setContent({ ...content, [listKey]: next }, tag)
  const enforced = [...policies, ...silos].filter((x) => x.enforce).length

  return (
    <div className="grid min-w-0 gap-4 [&>*]:min-w-0">
      <div className="flex gap-3 rounded-xl border bg-card px-4 py-3 text-[13px] text-muted-foreground">
        <ShieldCheck className="mt-0.5 size-4 shrink-0 text-sky-600 dark:text-sky-400" />
        <p className="min-w-0">
          Richtlinien legen fest, von welchen Geräten sich Konten anmelden dürfen. Silos ordnen Konten einer Richtlinie zu.
          Voraussetzung ist die Domänenfunktionsebene Windows Server 2012 R2 oder höher. Neue Einträge starten im Überwachungsmodus
          {enforced > 0 ? <> – derzeit {enforced === 1 ? 'wird 1 Eintrag' : `werden ${enforced} Einträge`} erzwungen.</> : '.'}
        </p>
      </div>
      <Tabs value={tab} onValueChange={(v) => setTab(v as TabKey)}>
        <div className="max-w-full overflow-x-auto">
          <TabsList aria-label="Bereiche der Authentication Silos">
            <TabsTrigger value="policies" className="max-sm:[&>svg]:hidden"><KeyRound /> Richtlinien <Badge variant="muted" className="ml-0.5">{policies.length}</Badge></TabsTrigger>
            <TabsTrigger value="silos" className="max-sm:[&>svg]:hidden"><Boxes /> Silos <Badge variant="muted" className="ml-0.5">{silos.length}</Badge></TabsTrigger>
            <TabsTrigger value="sync" className="max-sm:[&>svg]:hidden"><MonitorSmartphone /> <span><span className="hidden sm:inline">Gerätegruppen-</span>Synchronisierung</span> <Badge variant="muted" className="ml-0.5">{sync.length}</Badge></TabsTrigger>
          </TabsList>
        </div>
        <TabsContent value="policies">
          <PoliciesList items={policies} onItemsChange={bind('authenticationPolicies')} readOnly={props.readOnly} />
        </TabsContent>
        <TabsContent value="silos">
          <SilosList items={silos} onItemsChange={bind('authenticationPolicySilos')} readOnly={props.readOnly} policies={policies} />
        </TabsContent>
        <TabsContent value="sync">
          <SyncList items={sync} onItemsChange={bind('deviceGroupSync')} readOnly={props.readOnly} />
        </TabsContent>
      </Tabs>
    </div>
  )
}

