import * as React from 'react'
import { useQuery } from '@tanstack/react-query'
import { Boxes, KeyRound, MonitorSmartphone, ShieldCheck, UserRound } from 'lucide-react'
import { Badge } from '@/components/ui/badge'
import { Input, Textarea } from '@/components/ui/input'
import { Field } from '@/components/ui/label'
import { MultiCombobox } from '@/components/ui/multi-combobox'
import type { ComboOption } from '@/components/ui/combobox'
import { Select } from '@/components/ui/select'
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs'
import { describeSignInRule } from '@/features/runs/plan-model'
import { tierOf, type Tier } from '@/lib/tier'
import { authPolicyTierIssues, authSiloTierIssues, authTier, deviceSyncTierIssues } from '@/lib/tier-rules'
import { ListEditor, type FormProps, type Item } from './list-editor'
import { FormSection, SwitchRow, setField, useOuOptions } from './form-helpers'
import { PrincipalCombobox, PrincipalMultiCombobox } from './lookups'
import { useSectionContent } from './draft-store'
import { sectionQuery } from './queries'
import { useGroupTierMap } from './tier-rule-alerts'
import type { EditorProps } from './editors'
import { t } from '@/i18n'

/* Authentication policies, authentication policy silos and device group synchronisation
 * (tiermodel-authsilos.json). The SDDL is generated by the framework; the form only shows the rule in words. */

export const TGT_MIN = 45
export const TGT_MAX = 600
const NONE = '__none'
const AUTO = 'auto'

/** "OU=Tier 0 Accounts,OU=Tier 0,OU=Admin,{{DOMAIN_DN}}" → "Admin › Tier 0 › Tier 0 Accounts" */
export function ouLabel(dn: string): string {
  const rel = dn.replace(/,?\{\{DOMAIN_DN\}\}$/i, '')
  if (!rel) return t('config.authsiloEditor.domainRoot')
  return rel
    .split(/,(?=\s*[A-Za-z]+=)/)
    .map((p) => p.trim().replace(/^[A-Za-z]+=/, ''))
    .reverse()
    .join(' › ')
}

const lastRdn = (dn: string) => ouLabel(dn).split(' › ').pop() ?? dn

const strings = (v: unknown): string[] => (Array.isArray(v) ? v.filter((x): x is string => typeof x === 'string' && !!x) : [])

function itemTier(o: Item): Tier {
  const tt = authTier(o)
  return tt === 0 || tt === 1 || tt === 2 ? tt : tierOf(o.name ?? o.group)
}

function ModeBadge({ enforce }: { enforce: unknown }) {
  return enforce ? <Badge variant="danger">{t('config.authsiloEditor.enforced')}</Badge> : <Badge variant="info">{t('config.authsiloEditor.audit')}</Badge>
}

function RulePreview({ title = t('config.authsiloEditor.effect'), children }: { title?: string; children: React.ReactNode }) {
  return (
    <div className="rounded-lg border border-dashed bg-muted/30 px-3.5 py-3" aria-live="polite">
      <p className="text-[11px] font-medium tracking-wide text-muted-foreground uppercase">{title}</p>
      <div className="mt-1 text-[13px] leading-relaxed">{children}</div>
    </div>
  )
}

function TierSelect({ value, onChange, id }: { value: Item; onChange: (v: Item) => void; id: string }) {
  return (
    <Field label={t('config.authsiloEditor.tier')} htmlFor={id} hint={t('config.authsiloEditor.forClassificationInTheAudit')}>
      <Select
        id={id}
        value={value.tier === 0 || value.tier === 1 || value.tier === 2 ? String(value.tier) : AUTO}
        onValueChange={(v) => onChange(setField(value, 'tier', v === AUTO ? undefined : Number(v), true))}
        options={[
          { value: AUTO, label: t('config.authsiloEditor.automaticFromTheName') },
          { value: '0', label: t('config.authsiloEditor.tier0') },
          { value: '1', label: t('config.authsiloEditor.tier1') },
          { value: '2', label: t('config.authsiloEditor.tier2') },
        ]}
      />
    </Field>
  )
}

function CommentField({ value, onChange, id }: { value: Item; onChange: (v: Item) => void; id: string }) {
  return (
    <Field label={t('config.authsiloEditor.comment')} htmlFor={id}>
      <Textarea id={id} rows={2} value={value.comment ?? ''} onChange={(e) => onChange(setField(value, 'comment', e.target.value, !('comment' in value)))} />
    </Field>
  )
}

/** Sentence for a policy's sign-in rule. */
export function policyRuleText(p: Item | undefined): string {
  const from = (p?.allowedToAuthenticateFrom ?? {}) as Item
  return describeSignInRule(!!from.includeDomainControllers, strings(from.deviceGroups))
}

function useAuthContent() {
  useQuery(sectionQuery('authsilos'))
  return useSectionContent('authsilos') as Item | undefined
}

// ============================================================ policies

function PolicyForm({ value, onChange, errors }: FormProps) {
  const from = (value.allowedToAuthenticateFrom ?? {}) as Item
  const setFrom = (key: string, v: unknown) => onChange({ ...value, allowedToAuthenticateFrom: { ...from, [key]: v } })
  const tgt = value.userTgtLifetimeMins
  return (
    <>
      <FormSection title={t('config.authsiloEditor.general')}>
        <Field label={t('common.name')} htmlFor="ap-name" required error={errors.name}>
          <Input id="ap-name" value={value.name ?? ''} onChange={(e) => onChange(setField(value, 'name', e.target.value))} aria-invalid={!!errors.name} placeholder={t('config.authsiloEditor.eGTier0Authentication')} />
        </Field>
        <Field label={t('config.authsiloEditor.description')} htmlFor="ap-desc">
          <Textarea id="ap-desc" rows={2} value={value.description ?? ''} onChange={(e) => onChange(setField(value, 'description', e.target.value))} />
        </Field>
        <SwitchRow
          id="ap-enforce"
          label={t('config.authsiloEditor.enforce')}
          description={value.enforce ? t('config.authsiloEditor.signInsThatViolateThe') : t('config.authsiloEditor.auditModeViolationsAreOnly')}
          checked={!!value.enforce}
          onCheckedChange={(v) => onChange(setField(value, 'enforce', v))}
        />
        <Field
          label={t('config.authsiloEditor.tgtLifetimeMinutes')}
          htmlFor="ap-tgt"
          error={errors.userTgtLifetimeMins}
          hint={t('config.authsiloEditor.tgtMinToTgtMax', { tGT_MIN: TGT_MIN, tGT_MAX: TGT_MAX })}
        >
          <Input
            id="ap-tgt"
            type="number"
            inputMode="numeric"
            className="max-w-40"
            value={tgt === null || tgt === undefined ? '' : String(tgt)}
            onChange={(e) => onChange(setField(value, 'userTgtLifetimeMins', e.target.value === '' ? null : Number(e.target.value)))}
            aria-invalid={!!errors.userTgtLifetimeMins}
          />
        </Field>
      </FormSection>
      <FormSection title={t('config.authsiloEditor.signInAllowedFrom')} description={t('config.authsiloEditor.theConditionAppliesToThe')}>
        <SwitchRow
          id="ap-dcs"
          label={t('config.authsiloEditor.domainControllers')}
          description={t('config.authsiloEditor.signInOnAnyDomain')}
          checked={!!from.includeDomainControllers}
          onCheckedChange={(v) => setFrom('includeDomainControllers', v)}
        />
        <Field label={t('config.authsiloEditor.deviceGroups')} htmlFor="ap-groups" error={errors.deviceGroups} hint={t('config.authsiloEditor.signInFromComputersThat')}>
          <PrincipalMultiCombobox id="ap-groups" values={strings(from.deviceGroups)} onChange={(v) => setFrom('deviceGroups', v)} placeholder={t('config.authsiloEditor.searchAndAddComputerGroup')} />
        </Field>
        <RulePreview>{policyRuleText(value)}</RulePreview>
      </FormSection>
      <TierSelect value={value} onChange={onChange} id="ap-tier" />
      <CommentField value={value} onChange={onChange} id="ap-comment" />
    </>
  )
}

function PoliciesList({ items, onItemsChange, readOnly }: { items: Item[]; onItemsChange: (n: Item[], tag?: string) => void; readOnly: boolean }) {
  const groupTiers = useGroupTierMap()
  return (
    <ListEditor
      items={items}
      onItemsChange={onItemsChange}
      hints={(p) => authPolicyTierIssues(p, groupTiers)}
      columns={[
        { id: 'name', header: t('common.name'), cell: (p) => <span className="block min-w-[120px] font-medium">{p.name}</span>, sortValue: (p) => p.name ?? '' },
        { id: 'mode', header: t('config.authsiloEditor.mode'), cell: (p) => <ModeBadge enforce={p.enforce} />, sortValue: (p) => (p.enforce ? 1 : 0) },
        {
          id: 'rule', header: t('config.authsiloEditor.signIn'),
          cell: (p) => <span className="line-clamp-2 min-w-[180px] max-w-md text-muted-foreground">{policyRuleText(p)}</span>,
          className: 'hidden @2xl:table-cell',
        },
        {
          id: 'tgt', header: t('config.authsiloEditor.tgt'), cell: (p) => (typeof p.userTgtLifetimeMins === 'number' ? `${p.userTgtLifetimeMins} min` : <span className="text-muted-foreground">{t('config.authsiloEditor.unchanged')}</span>),
          sortValue: (p) => p.userTgtLifetimeMins ?? 0, className: 'hidden @4xl:table-cell',
        },
      ]}
      searchText={(p) => `${p.name} ${p.description ?? ''} ${strings(p.allowedToAuthenticateFrom?.deviceGroups).join(' ')} ${p.comment ?? ''}`}
      tierOf={itemTier}
      itemLabel={(p) => p.name}
      newItem={() => ({ name: '', description: '', enforce: false, userTgtLifetimeMins: 240, allowedToAuthenticateFrom: { includeDomainControllers: false, deviceGroups: [] }, comment: '' })}
      Form={PolicyForm}
      entity={{ singular: t('config.authsiloEditor.policy'), plural: t('config.authsiloEditor.policies'), article: 'die' }}
      readOnly={readOnly}
      defaultSort="name"
      validate={(p, all, index) => validatePolicy(p, all, index)}
    />
  )
}

export function validatePolicy(p: Item, all: Item[], index: number | null): Record<string, string> {
  const e: Record<string, string> = {}
  const name = String(p.name ?? '').trim()
  if (!name) e.name = t('config.authsiloEditor.nameIsRequired')
  else if (all.some((x, i) => i !== index && String(x.name ?? '').trim().toLowerCase() === name.toLowerCase())) e.name = t('config.authsiloEditor.aPolicyWithThisName')
  const tgt = p.userTgtLifetimeMins
  if (tgt !== null && tgt !== undefined && (!Number.isInteger(tgt) || tgt < TGT_MIN || tgt > TGT_MAX))
    e.userTgtLifetimeMins = t('config.authsiloEditor.pleaseEnterAWholeNumber', { tGT_MIN: TGT_MIN, tGT_MAX: TGT_MAX })
  return e
}

// ============================================================ silos

function usePolicyOptions() {
  const content = useAuthContent()
  const policies = strings((content?.authenticationPolicies ?? []).map((p: Item) => p.name))
  return [{ value: NONE, label: t('config.authsiloEditor.none') }, ...policies.map((n) => ({ value: n, label: n }))]
}

function useAccountOptions(): ComboOption[] {
  useQuery(sectionQuery('users'))
  const users = useSectionContent('users') as Item | undefined
  return React.useMemo(
    () =>
      ((users?.users ?? []) as Item[])
        .filter((u) => u.samAccountName)
        .map((u) => ({ value: String(u.samAccountName), label: String(u.samAccountName), hint: u.displayName || u.ouPath, icon: <UserRound className="size-4 text-muted-foreground" /> })),
    [users],
  )
}

function SiloForm({ value, onChange, errors }: FormProps) {
  const policyOptions = usePolicyOptions()
  const ouOptions = useOuOptions()
  const accountOptions = useAccountOptions()
  const content = useAuthContent()
  const members = (value.members ?? {}) as Item
  const setMembers = (key: string, v: string[]) => onChange({ ...value, members: { ...members, [key]: v } })
  const policy = (field: string) => (
    <Select
      id={`as-${field}`}
      value={value[field] ? String(value[field]) : NONE}
      onValueChange={(v) => onChange(setField(value, field, v === NONE ? '' : v))}
      options={policyOptions.some((o) => o.value === value[field]) || !value[field] ? policyOptions : [...policyOptions, { value: String(value[field]), label: t('config.authsiloEditor.valueNotConfigured', { value: value[field] }) }]}
    />
  )
  const userPolicy = (content?.authenticationPolicies ?? []).find((p: Item) => p.name === value.userAuthenticationPolicy) as Item | undefined
  const userOus = strings(members.userOUs)
  const computerOus = strings(members.computerOUs)
  const computerGroups = strings(members.computerGroups)
  const excluded = strings(members.excludeAccounts)

  return (
    <>
      <FormSection title={t('config.authsiloEditor.general')}>
        <Field label={t('common.name')} htmlFor="as-name" required error={errors.name}>
          <Input id="as-name" value={value.name ?? ''} onChange={(e) => onChange(setField(value, 'name', e.target.value))} aria-invalid={!!errors.name} placeholder={t('config.authsiloEditor.eGTier0Authentication2')} />
        </Field>
        <Field label={t('config.authsiloEditor.description')} htmlFor="as-desc">
          <Textarea id="as-desc" rows={2} value={value.description ?? ''} onChange={(e) => onChange(setField(value, 'description', e.target.value))} />
        </Field>
        <SwitchRow
          id="as-enforce"
          label={t('config.authsiloEditor.enforce')}
          description={value.enforce ? t('config.authsiloEditor.theSiloSPoliciesAre') : t('config.authsiloEditor.auditModeViolationsAreOnly2')}
          checked={!!value.enforce}
          onCheckedChange={(v) => onChange(setField(value, 'enforce', v))}
        />
      </FormSection>
      <FormSection title={t('config.authsiloEditor.policies')} description={t('config.authsiloEditor.fromTheConfiguredAuthenticationPolicies')}>
        <Field label={t('config.authsiloEditor.forUserAccounts')} htmlFor="as-userAuthenticationPolicy" error={errors.userAuthenticationPolicy}>{policy('userAuthenticationPolicy')}</Field>
        <div className="grid gap-4 sm:grid-cols-2">
          <Field label={t('config.authsiloEditor.forComputerAccounts')} htmlFor="as-computerAuthenticationPolicy" error={errors.computerAuthenticationPolicy}>{policy('computerAuthenticationPolicy')}</Field>
          <Field label={t('config.authsiloEditor.forServiceAccountsMsa')} htmlFor="as-serviceAuthenticationPolicy" error={errors.serviceAuthenticationPolicy}>{policy('serviceAuthenticationPolicy')}</Field>
        </div>
      </FormSection>
      <FormSection title={t('config.authsiloEditor.members')} description={t('config.authsiloEditor.accountsArePermittedInThe')}>
        <Field label={t('config.authsiloEditor.userOus')} htmlFor="as-userous" hint={t('config.authsiloEditor.allUsersBelowTheseOus')}>
          <MultiCombobox id="as-userous" values={userOus} onChange={(v) => setMembers('userOUs', v)} options={ouOptions} placeholder={t('config.authsiloEditor.searchAndAddOu')} allowCustom={false} />
        </Field>
        <Field label={t('config.authsiloEditor.computerOus')} htmlFor="as-compous" hint={t('config.authsiloEditor.allComputersBelowTheseOus')}>
          <MultiCombobox id="as-compous" values={computerOus} onChange={(v) => setMembers('computerOUs', v)} options={ouOptions} placeholder={t('config.authsiloEditor.searchAndAddOu')} allowCustom={false} />
        </Field>
        <Field label={t('config.authsiloEditor.computerGroups')} htmlFor="as-compgroups" hint={t('config.authsiloEditor.computersThatAreDirectMembers')}>
          <PrincipalMultiCombobox id="as-compgroups" values={computerGroups} onChange={(v) => setMembers('computerGroups', v)} placeholder={t('config.authsiloEditor.searchAndAddGroup')} />
        </Field>
        <Field label={t('config.authsiloEditor.excludedAccounts')} htmlFor="as-exclude" hint={t('config.authsiloEditor.samaccountnameNeverIncludedEG')}>
          <MultiCombobox id="as-exclude" values={excluded} onChange={(v) => setMembers('excludeAccounts', v)} options={accountOptions} placeholder={t('config.authsiloEditor.searchOrEnterAccount')} />
        </Field>
        <RulePreview>
          <SiloSentence silo={value} userPolicy={userPolicy} />
        </RulePreview>
      </FormSection>
      <TierSelect value={value} onChange={onChange} id="as-tier" />
      <CommentField value={value} onChange={onChange} id="as-comment" />
    </>
  )
}

function SiloSentence({ silo, userPolicy }: { silo: Item; userPolicy: Item | undefined }) {
  const m = (silo.members ?? {}) as Item
  const who: string[] = []
  const userOus = strings(m.userOUs)
  const computerOus = strings(m.computerOUs)
  const groups = strings(m.computerGroups)
  if (userOus.length) who.push(t('config.authsiloEditor.allUsersUnderJoin', { join: userOus.map(lastRdn).join(', ') }))
  if (computerOus.length) who.push(t('config.authsiloEditor.allComputersUnderJoin', { join: computerOus.map(lastRdn).join(', ') }))
  if (groups.length) who.push(t('config.authsiloEditor.computersOfGroups', { count: groups.length, groups: groups.join(', ') }))
  const excluded = strings(m.excludeAccounts)
  return (
    <>
      {who.length ? (
        <p>
          {t('config.authsiloEditor.included', { who: who.join(', ') })}
          {excluded.length ? t('config.authsiloEditor.exceptJoin', { join: excluded.join(', ') }) : ''}.
        </p>
      ) : (
        <p className="text-muted-foreground">{t('config.authsiloEditor.noMembersDefinedYet')}</p>
      )}
      <p className="mt-1">
        {silo.userAuthenticationPolicy ? (
          <>{t('config.authsiloEditor.forTheirUserAccounts')} {policyRuleText(userPolicy)}{userPolicy ? '.' : t('config.authsiloEditor.policyIsNotConfigured')}</>
        ) : (
          <span className="text-muted-foreground">{t('config.authsiloEditor.withoutAUserPolicyThe')}</span>
        )}
      </p>
      <p className="mt-1 text-muted-foreground">{silo.enforce ? t('config.authsiloEditor.theSiloIsEnforced') : t('config.authsiloEditor.theSiloRunsInAudit')}</p>
    </>
  )
}

function SilosList({ items, onItemsChange, readOnly, policies }: { items: Item[]; onItemsChange: (n: Item[], tag?: string) => void; readOnly: boolean; policies: Item[] }) {
  const groupTiers = useGroupTierMap()
  return (
    <ListEditor
      items={items}
      onItemsChange={onItemsChange}
      hints={(s) => authSiloTierIssues(s, policies, groupTiers)}
      columns={[
        { id: 'name', header: t('common.name'), cell: (s) => <span className="block min-w-[120px] font-medium">{s.name}</span>, sortValue: (s) => s.name ?? '' },
        { id: 'mode', header: t('config.authsiloEditor.mode'), cell: (s) => <ModeBadge enforce={s.enforce} />, sortValue: (s) => (s.enforce ? 1 : 0) },
        { id: 'policy', header: t('config.authsiloEditor.userPolicy'), cell: (s) => s.userAuthenticationPolicy || <span className="text-muted-foreground">–</span>, sortValue: (s) => s.userAuthenticationPolicy ?? '', className: 'hidden @2xl:table-cell' },
        {
          id: 'members', header: t('config.authsiloEditor.members'),
          cell: (s) => {
            const m = (s.members ?? {}) as Item
            const parts = [...strings(m.userOUs), ...strings(m.computerOUs)].map(lastRdn).concat(strings(m.computerGroups))
            return <span className="line-clamp-2 max-w-sm text-muted-foreground">{parts.join(', ') || '–'}</span>
          },
          className: 'hidden @4xl:table-cell',
        },
      ]}
      searchText={(s) => `${s.name} ${s.description ?? ''} ${s.userAuthenticationPolicy ?? ''} ${JSON.stringify(s.members ?? {})}`}
      tierOf={itemTier}
      itemLabel={(s) => s.name}
      newItem={() => ({
        name: '', description: '', enforce: false, userAuthenticationPolicy: '', computerAuthenticationPolicy: '', serviceAuthenticationPolicy: '',
        members: { userOUs: [], computerGroups: [], computerOUs: [], excludeAccounts: [] }, comment: '',
      })}
      Form={SiloForm}
      entity={{ singular: t('config.authsiloEditor.silo'), plural: t('config.authsiloEditor.silos'), article: 'das' }}
      readOnly={readOnly}
      defaultSort="name"
      validate={(s, all, index) => validateSilo(s, all, index, policies)}
    />
  )
}

export function validateSilo(s: Item, all: Item[], index: number | null, policies: Item[]): Record<string, string> {
  const e: Record<string, string> = {}
  const name = String(s.name ?? '').trim()
  if (!name) e.name = t('config.authsiloEditor.nameIsRequired')
  else if (all.some((x, i) => i !== index && String(x.name ?? '').trim().toLowerCase() === name.toLowerCase())) e.name = t('config.authsiloEditor.aSiloWithThisName')
  const known = new Set(policies.map((p) => String(p.name ?? '').toLowerCase()))
  for (const field of ['userAuthenticationPolicy', 'computerAuthenticationPolicy', 'serviceAuthenticationPolicy'])
    if (s[field] && !known.has(String(s[field]).toLowerCase())) e[field] = t('config.authsiloEditor.thisPolicyIsNotConfigured')
  return e
}

// ============================================================ device group sync

function SyncForm({ value, onChange, errors }: FormProps) {
  const ouOptions = useOuOptions()
  const sources = strings(value.sourceOUs)
  return (
    <>
      <FormSection title={t('config.authsiloEditor.deviceGroup')}>
        <Field label={t('config.authsiloEditor.group')} htmlFor="ds-group" required error={errors.group} hint={t('config.authsiloEditor.samaccountnameOfTheComputerGroup')}>
          <PrincipalCombobox id="ds-group" value={value.group ?? ''} onChange={(v) => onChange(setField(value, 'group', v))} placeholder={t('config.authsiloEditor.selectGroup')} invalid={!!errors.group} />
        </Field>
        <Field label={t('config.authsiloEditor.sourceOus')} htmlFor="ds-ous" required error={errors.sourceOUs} hint={t('config.authsiloEditor.allComputersBelowTheseOus2')}>
          <MultiCombobox id="ds-ous" values={sources} onChange={(v) => onChange(setField(value, 'sourceOUs', v))} options={ouOptions} placeholder={t('config.authsiloEditor.searchAndAddOu')} allowCustom={false} invalid={!!errors.sourceOUs} />
        </Field>
        <RulePreview>
          {value.group && sources.length ? (
            <p>{t('config.authsiloEditor.syncSentence', { sources: sources.map(lastRdn).join(', '), group: value.group })}</p>
          ) : (
            <p className="text-muted-foreground">{t('config.authsiloEditor.selectAGroupAndAt')}</p>
          )}
        </RulePreview>
      </FormSection>
      <TierSelect value={value} onChange={onChange} id="ds-tier" />
      <CommentField value={value} onChange={onChange} id="ds-comment" />
    </>
  )
}

function SyncList({ items, onItemsChange, readOnly }: { items: Item[]; onItemsChange: (n: Item[], tag?: string) => void; readOnly: boolean }) {
  const groupTiers = useGroupTierMap()
  return (
    <ListEditor
      items={items}
      onItemsChange={onItemsChange}
      hints={(d) => deviceSyncTierIssues(d, groupTiers)}
      columns={[
        { id: 'group', header: t('config.authsiloEditor.deviceGroup'), cell: (d) => <span className="font-medium">{d.group}</span>, sortValue: (d) => d.group ?? '' },
        {
          id: 'sources', header: t('config.authsiloEditor.sourceOus'),
          cell: (d) => <span className="line-clamp-2 max-w-md text-muted-foreground">{strings(d.sourceOUs).map(ouLabel).join('; ') || '–'}</span>,
        },
      ]}
      searchText={(d) => `${d.group} ${strings(d.sourceOUs).join(' ')} ${d.comment ?? ''}`}
      tierOf={(d) => (d.tier === 0 || d.tier === 1 || d.tier === 2 ? d.tier : tierOf(d.group))}
      itemLabel={(d) => d.group}
      newItem={() => ({ group: '', sourceOUs: [], comment: '' })}
      Form={SyncForm}
      entity={{ singular: t('config.authsiloEditor.synchronization'), plural: t('config.authsiloEditor.synchronizations'), article: 'die' }}
      readOnly={readOnly}
      defaultSort="group"
      validate={(d, all, index) => validateSync(d, all, index)}
    />
  )
}

export function validateSync(d: Item, all: Item[], index: number | null): Record<string, string> {
  const e: Record<string, string> = {}
  const group = String(d.group ?? '').trim()
  if (!group) e.group = t('config.authsiloEditor.groupIsRequired')
  else if (all.some((x, i) => i !== index && String(x.group ?? '').trim().toLowerCase() === group.toLowerCase())) e.group = t('config.authsiloEditor.aSynchronizationAlreadyExistsFor')
  if (!strings(d.sourceOUs).length) e.sourceOUs = t('config.authsiloEditor.selectAtLeastOneSource')
  return e
}

// ============================================================ section editor

type TabKey = 'policies' | 'silos' | 'sync'

export function AuthSilosEditor(props: EditorProps) {
  const content = (props.content ?? {}) as Item
  const policies: Item[] = Array.isArray(content.authenticationPolicies) ? content.authenticationPolicies : []
  const silos: Item[] = Array.isArray(content.authenticationPolicySilos) ? content.authenticationPolicySilos : []
  const sync: Item[] = Array.isArray(content.deviceGroupSync) ? content.deviceGroupSync : []
  const [tab, setTab] = React.useState<TabKey>('policies')
  const bind = (listKey: string) => (next: Item[], tag?: string) => props.setContent({ ...content, [listKey]: next }, tag)
  const enforced = [...policies, ...silos].filter((x) => x.enforce).length

  return (
    <div className="grid min-w-0 gap-4 [&>*]:min-w-0">
      <div className="flex gap-3 rounded-xl border bg-card px-4 py-3 text-[13px] text-muted-foreground">
        <ShieldCheck className="mt-0.5 size-4 shrink-0 text-sky-600 dark:text-sky-400" />
        <p className="min-w-0">
          {t('config.authsiloEditor.policiesDefineFromWhichDevices')}
          {enforced > 0 ? t('config.authsiloEditor.enforcedNow', { count: enforced }) : '.'}
        </p>
      </div>
      <Tabs value={tab} onValueChange={(v) => setTab(v as TabKey)}>
        <div className="max-w-full overflow-x-auto">
          <TabsList aria-label={t('config.authsiloEditor.areasOfTheAuthenticationSilos')}>
            <TabsTrigger value="policies" className="max-sm:[&>svg]:hidden"><KeyRound /> {t('config.authsiloEditor.policies')} <Badge variant="muted" className="ml-0.5">{policies.length}</Badge></TabsTrigger>
            <TabsTrigger value="silos" className="max-sm:[&>svg]:hidden"><Boxes /> {t('config.authsiloEditor.silos')} <Badge variant="muted" className="ml-0.5">{silos.length}</Badge></TabsTrigger>
            <TabsTrigger value="sync" className="max-sm:[&>svg]:hidden"><MonitorSmartphone /> <span><span className="hidden sm:inline">{t('config.authsiloEditor.deviceGroup2')}</span>{t('config.authsiloEditor.synchronization2')}</span> <Badge variant="muted" className="ml-0.5">{sync.length}</Badge></TabsTrigger>
          </TabsList>
        </div>
        <TabsContent value="policies">
          <PoliciesList items={policies} onItemsChange={bind('authenticationPolicies')} readOnly={props.readOnly} />
        </TabsContent>
        <TabsContent value="silos">
          <SilosList items={silos} onItemsChange={bind('authenticationPolicySilos')} readOnly={props.readOnly} policies={policies} />
        </TabsContent>
        <TabsContent value="sync">
          <SyncList items={sync} onItemsChange={bind('deviceGroupSync')} readOnly={props.readOnly} />
        </TabsContent>
      </Tabs>
    </div>
  )
}

