/* German labels for configuration keys – shared by the structured object form, the change list
 * (save dialog / versions) and the change log. Unknown keys are humanized from camelCase. */

export const fieldLabels: Record<string, string> = {
  // general
  name: 'Name',
  displayName: 'Anzeigename',
  description: 'Beschreibung',
  comment: 'Kommentar',
  version: 'Version',
  schemaVersion: 'Schema-Version',
  author: 'Autor',
  created: 'Erstellt',
  lastModified: 'Zuletzt geändert',
  lastUpdated: 'Zuletzt aktualisiert',
  metadata: 'Metadaten',
  enabled: 'Aktiviert',
  type: 'Typ',
  mode: 'Modus',
  method: 'Methode',
  path: 'Übergeordnete OU',
  tier: 'Tier',
  token: 'Platzhalter',
  property: 'Eigenschaft',
  operator: 'Operator',
  conditions: 'Bedingungen',
  names: 'Namen',
  principals: 'Prinzipale',
  right: 'Recht',
  // OUs
  organizationUnits: 'Organisationseinheiten',
  protectFromAccidentalDeletion: 'Löschschutz',
  disableInheritance: 'ACL-Vererbung deaktiviert',
  blockGpoInheritance: 'GPO-Vererbung blockiert',
  // groups / users
  groups: 'Gruppen',
  samaccountname: 'sAMAccountName',
  samAccountName: 'sAMAccountName',
  groupscope: 'Gruppenbereich',
  groupcategory: 'Gruppentyp',
  users: 'Benutzer',
  ouPath: 'Ziel-OU',
  memberOf: 'Mitglied von',
  memberGroups: 'Mitgliedsgruppen',
  membershipGroups: 'Mitgliedschaften',
  conditionalGroups: 'Bedingte Gruppen',
  emptyGroups: 'Leere Gruppen',
  forestRootOnly: 'Nur Stammdomäne',
  // ACLs
  aclDelegations: 'Delegationen',
  targetOUPath: 'Ziel-OU',
  identityreference: 'Prinzipal',
  activedirectoryrights: 'Rechte',
  accesscontroltype: 'Zugriffstyp',
  activeDirectorysecurityinheritance: 'Vererbung',
  objecttype: 'Objekttyp',
  inheritedObjectType: 'Geerbter Objekttyp',
  inheritedobjecttype: 'Geerbter Objekttyp',
  inheritanceType: 'Vererbungstyp',
  resolveguid: 'GUID auflösen',
  managedServiceAccountType: 'Kontotyp',
  // Windows LAPS
  winLapsDelegations: 'LAPS-Delegationen',
  ouDn: 'OU',
  computerSelfPermission: 'Computer-Selbstberechtigung',
  isDomainControllerOu: 'Domain-Controller-OU',
  readGroup: 'Lesegruppe',
  resetGroup: 'Zurücksetzen-Gruppe',
  decryptorGroup: 'Entschlüsselungsgruppe',
  decryptorGpoName: 'Decryptor-GPO',
  // GPOs
  gpos: 'Gruppenrichtlinien',
  ImportOnlyGpo: 'Importierte GPOs',
  PostConfigureGpo: 'Nachkonfigurierte GPOs',
  TemplateGpos: 'Vorlagen-GPOs',
  importPath: 'Importpfad',
  gpoStatus: 'GPO-Status',
  gpoComment: 'GPO-Kommentar',
  linkOrder: 'Verknüpfungsreihenfolge',
  linkEnabled: 'Verknüpfung aktiv',
  rename: 'Umbenennen in',
  denyApplyGroupPolicy: '„Gruppenrichtlinie übernehmen“ verweigern',
  restrictedGroups: 'Eingeschränkte Gruppen',
  userRightsAssignments: 'Zuweisen von Benutzerrechten',
  groupSidOrName: 'Gruppe (SID oder Name)',
  literalStrings: 'Literale Zeichenfolgen',
  resolvableGroups: 'Auflösbare Gruppen',
  // ADMX / ADML
  admx: 'ADMX',
  adml: 'ADML',
  destinationPath: 'Zielpfad',
  sourcePath: 'Quellpfad',
  files: 'Dateien',
  hash: 'Hash (MD5)',
  hashDate: 'Hash-Datum',
  downloadLink: 'Download-Link',
  // GUID mappings
  staticMappings: 'Statische Zuordnungen',
  dynamicMappings: 'Dynamische Zuordnungen',
  objectClasses: 'Objektklassen',
  extendedRights: 'Erweiterte Rechte',
  attributes: 'Attribute',
  specialValues: 'Sonderwerte',
  friendlyNameMappings: 'Aliasnamen',
  // dependencies
  pester: 'Pester-Version',
  modules: 'Module',
  // metadata
  conditionalLogic: 'Bedingte Logik',
  domainTypeDetection: 'Erkennung des Domänentyps',
  groupExistenceCheck: 'Prüfung auf vorhandene Gruppen',
  ignoreErrors: 'Fehler ignorieren',
  featureDetection: 'Funktionserkennung',
  adIntegratedDns: 'AD-integriertes DNS',
  principalTypes: 'Prinzipaltypen',
  group: 'Gruppe',
  user: 'Benutzer',
  ntService: 'NT-Dienst',
  wellKnownSid: 'Bekannte SID',
  resolutionMethod: 'Auflösungsmethode',
  sidProperty: 'SID-Eigenschaft',
  gpoLinkTargets: 'GPO-Verknüpfungsziele',
  domainRoot: 'Domänenstamm',
  ouPaths: 'OU-Pfade',
  // service settings / change log details
  section: 'Sektion',
  fromVersion: 'Von Version',
  toVersion: 'Auf Version',
  roleGroups: 'Rollengruppen',
  sid: 'SID',
  Admin: 'Administrator',
  Editor: 'Bearbeiter',
  Operator: 'Operator',
  Viewer: 'Leser',
  defaultPreferredDc: 'Standard-Domain-Controller',
  preferredDc: 'Domain Controller',
  admlLanguage: 'ADML-Sprache',
  runRetentionDays: 'Aufbewahrung (Tage)',
  requireApproval: 'Freigabe erforderlich',
  approvalTimeoutHours: 'Freigabefrist (Stunden)',
  publicBaseUrl: 'Öffentliche Adresse',
  scope: 'Bereich',
  includeMsa: 'MSA einbeziehen',
  includeGmsa: 'gMSA einbeziehen',
  includeDmsa: 'dMSA einbeziehen',
  includeWinLaps: 'Windows LAPS einbeziehen',
  confirmApply: 'Anwenden bestätigt',
  runId: 'Lauf',
  reason: 'Grund',
  username: 'Benutzername',
  role: 'Rolle',
  target: 'Ziel',
  events: 'Ereignisse',
  host: 'Server',
  port: 'Port',
  from: 'Absender',
  security: 'Verschlüsselung',
  cron: 'Zeitplan (Cron)',
  error: 'Fehler',
  ip: 'IP-Adresse',
  count: 'Anzahl',
  // deploy plan details
  groupScope: 'Gruppenbereich',
  groupCategory: 'Gruppentyp',
  principal: 'Prinzipal',
  identityReference: 'Prinzipal',
  rights: 'Rechte',
  activeDirectoryRights: 'Rechte',
  objectType: 'Objekttyp',
  inheritance: 'Vererbung',
  accessControlType: 'Zugriffstyp',
  backupId: 'Backup-ID',
  enforced: 'Erzwungen',
  addGroups: 'Hinzuzufügende Gruppen',
  removeGroups: 'Zu entfernende Gruppen',
  language: 'Sprache',
  distinguishedName: 'Distinguished Name',
  gpoName: 'GPO',
  file: 'Datei',
  existing: 'Vorhanden',
  reasonText: 'Begründung',
  // authentication silos
  authenticationPolicies: 'Authentifizierungsrichtlinien',
  authenticationPolicySilos: 'Silos',
  deviceGroupSync: 'Gerätegruppen-Synchronisierung',
  enforce: 'Erzwingen',
  userTgtLifetimeMins: 'TGT-Lebensdauer (Minuten)',
  allowedToAuthenticateFrom: 'Anmeldung erlaubt von',
  includeDomainControllers: 'Domänencontroller',
  deviceGroups: 'Gerätegruppen',
  deviceGroupSids: 'SIDs der Gerätegruppen',
  userAuthenticationPolicy: 'Richtlinie für Benutzer',
  computerAuthenticationPolicy: 'Richtlinie für Computer',
  serviceAuthenticationPolicy: 'Richtlinie für Dienstkonten',
  members: 'Mitglieder',
  userOUs: 'Benutzer-OUs',
  computerGroups: 'Computergruppen',
  computerOUs: 'Computer-OUs',
  excludeAccounts: 'Ausgenommene Konten',
  sourceOUs: 'Quell-OUs',
  sourceOU: 'Quell-OU',
  groupDn: 'Gruppe (DN)',
  computer: 'Computer',
  silo: 'Silo',
  account: 'Konto',
  accountType: 'Kontotyp',
  currentSilo: 'Aktuelles Silo',
  currentEnforce: 'Aktuell erzwungen',
  currentUserTgtLifetimeMins: 'Aktuelle TGT-Lebensdauer',
  changes: 'Änderungen',
  sddl: 'Sicherheitsbeschreibung',
  currentSddl: 'Aktuelle Sicherheitsbeschreibung',
}

/** "protectFromAccidentalDeletion" → "Protect from accidental deletion" (fallback for unknown field names).
 *  Map keys that are data (e.g. "msDS-ManagedServiceAccount", "ActiveDirectory", file names) stay as they are. */
export function humanizeKey(key: string): string {
  if (!/^[a-z][a-zA-Z0-9]*$/.test(key) && !/^[a-z]+(_[a-z0-9]+)+$/.test(key)) return key
  const words = key
    .replace(/_/g, ' ')
    .replace(/([a-z0-9])([A-Z])/g, '$1 $2')
    .replace(/([A-Z]+)([A-Z][a-z])/g, '$1 $2')
    .split(/\s+/)
  return words.map((w, i) => (i === 0 ? w.charAt(0).toUpperCase() + w.slice(1) : /^[A-Z]{2,}/.test(w) ? w : w.toLowerCase())).join(' ')
}

export function fieldLabel(key: string): string {
  return fieldLabels[key] ?? humanizeKey(key)
}
