function Import-TierModelGpo {
    <#
    .SYNOPSIS
    Execute TierModel GPO import from deployment plan.
    
    .DESCRIPTION
    Imports settings into existing GPOs from backup files based on the deployment plan
    generated by Get-TierModelGpo. Handles GPO import operations for both ImportOnlyGpo
    and standard GPO configuration workflows.
    
    .PARAMETER Plan
    Deployment plan object from Get-TierModelGpo containing GPO import actions to execute.
    
    .PARAMETER DomainController
    The domain controller to use for Active Directory operations.
    
    .EXAMPLE
    $plan = Get-TierModelGpo -Config $gpoConfig -DomainController "DC01"
    Import-TierModelGpo -Plan $plan -DomainController "DC01"
    
    .OUTPUTS
    PSCustomObject with execution results including success/failure counts and details.
    #>
    [CmdletBinding(SupportsShouldProcess)]
    param(
        [Parameter(Mandatory)]
        [object]$Plan,
        
        [Parameter(Mandatory)]
        [string]$DomainController
    )
    
    $CorrelationId = [System.Guid]::NewGuid().ToString()
    $startTime = Get-Date
    
    # Filter to only ImportGPO actions
    $importActions = @($Plan.Actions | Where-Object { $_.Action -eq 'ImportGPO' })
    
    Write-TierModelLog -Level Info -Message "GPO import start" -Data @{
        TotalActions = $importActions.Count
        DomainController = $DomainController
        WhatIf = $PSCmdlet.ShouldProcess
        CorrelationId = $CorrelationId
    } | Out-Null
    
    try {
        $executed = 0
        $failed = 0
        $skipped = 0
        $errors = @()
        $converged = $true
        
        foreach ($action in $importActions) {
            try {
                $gpoData = $action.Data
                $gpoName = $gpoData.name
                $targetOUPath = $action.Path
                
                # Import GPO from backup
                Write-TierModelLog -Level Info -Message "Importing GPO" -Data @{
                    Name = $gpoName
                    TargetOU = $targetOUPath
                }
                
                # GPO import starts (removed verbose message)
                
                if ($PSCmdlet.ShouldProcess("GPO: $gpoName", "Import GPO")) {
                    # Import GPO settings if path is specified (original working logic)
                    if ($gpoData.PSObject.Properties.Name -contains 'importPath' -and $gpoData.importPath) {
                        # ConfigPath already points to config directory, so use parent directory
                        $basePath = Split-Path $Plan.Config.ConfigPath -Parent
                        $importPath = Join-Path $basePath $gpoData.importPath
                        if (Test-Path $importPath) {
                            # Import source: $importPath (removed verbose message)
                            # Capture Import-GPO output to prevent it from interfering with our return object
                            $null = Import-GPO -BackupId (Split-Path $importPath -Leaf) -TargetName $gpoName -Path (Split-Path $importPath -Parent) -Server $DomainController
                            
                            Write-TierModelLog -Level Info -Message "GPO settings imported successfully" -Data @{
                                GPOName = $gpoName
                                ImportPath = $importPath
                                CorrelationId = $CorrelationId
                            } | Out-Null
                            
                            Write-Host "  ✅ Imported settings into GPO: $gpoName" -ForegroundColor Green
                            $executed++
                        } else {
                            $errorMsg = "Import path not found: $importPath"
                            Write-Host "    ERROR: $errorMsg" -ForegroundColor Red
                            
                            Write-TierModelLog -Level Error -Message "Failed to import GPO" -Data @{
                                GPOName = $gpoName
                                Exception = $errorMsg
                                CorrelationId = $CorrelationId
                            } | Out-Null
                            
                            $errors += $errorMsg
                            $failed++
                            $converged = $false
                        }
                    } else {
                        Write-Host "    Skipping import - no importPath specified" -ForegroundColor Yellow
                        $skipped++
                    }
                    
                } else {
                    Write-Host "  [WhatIf] Would import GPO: $gpoName" -ForegroundColor DarkYellow
                    $skipped++
                }
                
            } catch {
                Write-TierModelLog -Level Error -Message "Failed to import GPO" -Data @{
                    GPOName = $action.Data.name
                    Exception = $_.Exception.Message
                    CorrelationId = $CorrelationId
                } | Out-Null
                
                Write-Host "  ERROR: Failed to import GPO '$($action.Data.name)' - $($_.Exception.Message)" -ForegroundColor Red
                $errors += @{
                    Timestamp = Get-Date
                    Category = 'Execution'
                    Code = 'GPOImportFailed'
                    Message = $_.Exception.Message
                    Context = @{
                        Action = $action.Action
                        GPOName = $action.Data.name
                    }
                }
                $failed++
                $converged = $false
            }
        }
        
        $durationMs = ((Get-Date) - $startTime).TotalMilliseconds
        
        Write-TierModelLog -Level Info -Message "GPO import complete" -Data @{
            ExecutedActions = $executed
            FailedActions = $failed
            SkippedActions = $skipped
            DurationMs = $durationMs
            CorrelationId = $CorrelationId
        } | Out-Null
        
        return [PSCustomObject]@{
            Executed = $executed
            Failed = $failed
            Skipped = $skipped
            Errors = $errors
            DurationMs = $durationMs
            Converged = $converged
            CorrelationId = $CorrelationId
        }
        
    } catch {
        Write-TierModelLog -Level Error -Message "GPO import failed" -Data @{
            Exception = $_.Exception.Message
            CorrelationId = $CorrelationId
        } | Out-Null
        
        return [PSCustomObject]@{
            Executed = 0
            Failed = 1
            Skipped = 0
            Errors = @(@{
                Timestamp = Get-Date
                Category = 'Critical'
                Code = 'GPOImportFailed'
                Message = $_.Exception.Message
                Context = @{ CorrelationId = $CorrelationId }
            })
            DurationMs = ((Get-Date) - $startTime).TotalMilliseconds
            Converged = $false
            CorrelationId = $CorrelationId
        }
    }
}