function New-TierModelOu {
    <#
    .SYNOPSIS
    Apply OU creation plan by creating organizational units in Active Directory.
    
    .DESCRIPTION
    Executes OU creation actions from a plan generated by Get-TierModelOu.
    Creates OUs using New-ADOrganizationalUnit and applies optional inheritance
    settings (GPO inheritance blocking, security inheritance disabling).
    
    .PARAMETER Plan
    Plan object output from Get-TierModelOu containing Actions array.
    
    .PARAMETER DomainController
    Preferred domain controller for operations.
    
    .OUTPUTS
    PSCustomObject with Applied, Skipped, Errors, DurationMs, and Converged status.
    
    .EXAMPLE
    $config = Get-TierModelConfig
    $plan = Get-TierModelOu -Config $config -DomainController "DC01.contoso.com"
    $result = New-TierModelOu -Plan $plan -DomainController "DC01.contoso.com"
    
    .EXAMPLE
    $result = New-TierModelOu -Plan $plan -DomainController "DC01.contoso.com" -WhatIf
    #>
    [CmdletBinding(SupportsShouldProcess)]
    param(
        [Parameter(Mandatory)]
        [object]$Plan,
        
        [Parameter(Mandatory)]
        [string]$DomainController
    )
    
    $CorrelationId = $script:CorrelationId
    $startTime = Get-Date
    
    # Ensure we have a proper array for counting
    $createActions = @($Plan.Actions | Where-Object { $_.Action -eq 'CreateOU' })
    
    Write-TierModelLog -Level Info -Message "OuCreateStart" -Data @{
        CorrelationId = $CorrelationId
        DomainController = $DomainController
        WhatIf = $WhatIfPreference
        PlanActionCount = $createActions.Count
    } | Out-Null
    
    $applied = @()
    $skipped = @()
    $errors = @()
    
    try {
        if ($createActions.Count -eq 0) {
            Write-TierModelLog -Level Info -Message "No OU creation actions in plan" -Data @{
                CorrelationId = $CorrelationId
            } | Out-Null
        }
        
        foreach ($action in $createActions) {
            try {
                $ouData = $action.Data
                $ouName = $ouData.name
                $ouPath = $action.Path
                
                # Get description safely - use comment if description doesn't exist
                $ouDescription = if ($ouData.PSObject.Properties.Name -contains 'description') { 
                    $ouData.description 
                } elseif ($ouData.PSObject.Properties.Name -contains 'comment') { 
                    $ouData.comment 
                } else { 
                    $null 
                }
                
                Write-TierModelLog -Level Info -Message "OuCreateStart" -Data @{
                    Name = $ouName
                    Path = $ouPath
                    Description = $ouDescription
                    WhatIf = $WhatIfPreference
                    CorrelationId = $CorrelationId
                } | Out-Null
                
                if ($PSCmdlet.ShouldProcess("OU: $ouName", "Create organizational unit at $ouPath")) {
                    # Show creation progress
                    Write-Host "  ✅ Creating OU: $ouName" -ForegroundColor Green
                    
                    # Actual creation
                    $newOuParams = @{
                        Name = $ouName
                            Path = $ouPath
                            Server = $DomainController
                            Confirm = $false
                        }
                        
                        # Add optional properties if they exist
                        if ($ouDescription) {
                            $newOuParams['Description'] = $ouDescription
                        }
                        if ($ouData.PSObject.Properties.Name -contains 'protectFromAccidentalDeletion' -and $null -ne $ouData.protectFromAccidentalDeletion) {
                            $newOuParams['ProtectedFromAccidentalDeletion'] = $ouData.protectFromAccidentalDeletion
                        }
                        
                        $newOU = New-ADOrganizationalUnit @newOuParams -PassThru
                        
                        $actionsPerformed = @('CreateOU')
                        $warnings = @()
                        
                        # Configure GPO inheritance blocking if specified - apply, then VERIFY with retry/backoff.
                        # A silent no-op (Set-GPInheritance returns without error but the gPOptions attribute does
                        # not persist) must NOT be reported as success, so we read back Get-GPInheritance on the
                        # SAME DC and retry before recording a hard error.
                        if ($ouData.PSObject.Properties.Name -contains 'blockGpoInheritance' -and $ouData.blockGpoInheritance -eq $true) {
                            Write-TierModelLog -Level Info -Message "OuBlockGpoStart" -Data @{
                                OUName = $ouName
                                DistinguishedName = $newOU.DistinguishedName
                                CorrelationId = $CorrelationId
                            } | Out-Null

                            $gpoBlockVerified = $false
                            $gpoBlockAttempts = 0
                            $gpoBlockLastError = $null
                            $gpoBlockMaxAttempts = 4
                            while (-not $gpoBlockVerified -and $gpoBlockAttempts -lt $gpoBlockMaxAttempts) {
                                $gpoBlockAttempts++
                                try {
                                    Set-GPInheritance -Target $newOU.DistinguishedName -IsBlocked Yes -Server $DomainController -ErrorAction Stop | Out-Null
                                } catch {
                                    $gpoBlockLastError = $_.Exception.Message
                                }
                                try {
                                    $gpoInheritanceState = Get-GPInheritance -Target $newOU.DistinguishedName -Server $DomainController -ErrorAction Stop
                                    if ($gpoInheritanceState.GpoInheritanceBlocked -eq $true) { $gpoBlockVerified = $true; break }
                                } catch {
                                    $gpoBlockLastError = $_.Exception.Message
                                }
                                if (-not $gpoBlockVerified -and $gpoBlockAttempts -lt $gpoBlockMaxAttempts) {
                                    Start-Sleep -Milliseconds ([int](500 * [Math]::Pow(2, $gpoBlockAttempts - 1)))
                                }
                            }

                            if ($gpoBlockVerified) {
                                $actionsPerformed += 'BlockGpoInheritance'
                                Write-TierModelLog -Level Info -Message "OuBlockGpoSuccess" -Data @{
                                    OUName = $ouName
                                    DistinguishedName = $newOU.DistinguishedName
                                    Attempts = $gpoBlockAttempts
                                    CorrelationId = $CorrelationId
                                } | Out-Null
                            } else {
                                # Human-readable error surfaced to the user; raw exception kept in the log only.
                                $errors += @{
                                    Timestamp = Get-Date
                                    Category  = 'Execution'
                                    Code      = 'BlockGpoInheritanceUnverified'
                                    Message   = "Block GPO Inheritance flag was not set for OU '$ouName'. The setting was applied but could not be confirmed after $gpoBlockAttempts attempts."
                                    Context   = @{ Name = $ouName; DistinguishedName = $newOU.DistinguishedName; Attempts = $gpoBlockAttempts }
                                }
                                Write-Host "    `u{274C} Block GPO Inheritance flag was not set for OU '$ouName' (after $gpoBlockAttempts attempts)" -ForegroundColor Red
                                Write-TierModelLog -Level Error -Message "OuBlockGpoUnverified" -Data @{
                                    OUName = $ouName
                                    DistinguishedName = $newOU.DistinguishedName
                                    Attempts = $gpoBlockAttempts
                                    Error = $gpoBlockLastError
                                    CorrelationId = $CorrelationId
                                } | Out-Null
                            }
                        }
                        
                        # Configure security inheritance blocking if specified - apply, then VERIFY with retry/backoff.
                        if ($ouData.PSObject.Properties.Name -contains 'disableInheritance' -and $ouData.disableInheritance -eq $true) {
                            Write-TierModelLog -Level Info -Message "OuDisableSecInheritStart" -Data @{
                                OUName = $ouName
                                DistinguishedName = $newOU.DistinguishedName
                                CorrelationId = $CorrelationId
                            } | Out-Null

                            $secBlockVerified = $false
                            $secBlockAttempts = 0
                            $secBlockLastError = $null
                            $secBlockMaxAttempts = 4
                            while (-not $secBlockVerified -and $secBlockAttempts -lt $secBlockMaxAttempts) {
                                $secBlockAttempts++
                                try {
                                    # Get the current ACL and disable inheritance (preserve existing permissions)
                                    $acl = Get-Acl -Path "AD:\$($newOU.DistinguishedName)" -ErrorAction Stop
                                    $acl.SetAccessRuleProtection($true, $true)
                                    Set-Acl -Path "AD:\$($newOU.DistinguishedName)" -AclObject $acl -ErrorAction Stop | Out-Null
                                } catch {
                                    $secBlockLastError = $_.Exception.Message
                                }
                                try {
                                    $verifyAcl = Get-Acl -Path "AD:\$($newOU.DistinguishedName)" -ErrorAction Stop
                                    if ($verifyAcl.AreAccessRulesProtected -eq $true) { $secBlockVerified = $true; break }
                                } catch {
                                    $secBlockLastError = $_.Exception.Message
                                }
                                if (-not $secBlockVerified -and $secBlockAttempts -lt $secBlockMaxAttempts) {
                                    Start-Sleep -Milliseconds ([int](500 * [Math]::Pow(2, $secBlockAttempts - 1)))
                                }
                            }

                            if ($secBlockVerified) {
                                $actionsPerformed += 'DisableSecurityInheritance'
                                Write-TierModelLog -Level Info -Message "OuDisableSecInheritSuccess" -Data @{
                                    OUName = $ouName
                                    DistinguishedName = $newOU.DistinguishedName
                                    Attempts = $secBlockAttempts
                                    CorrelationId = $CorrelationId
                                } | Out-Null
                            } else {
                                # Human-readable error surfaced to the user; raw exception kept in the log only.
                                $errors += @{
                                    Timestamp = Get-Date
                                    Category  = 'Execution'
                                    Code      = 'DisableSecurityInheritanceUnverified'
                                    Message   = "Security Inheritance was not disabled for OU '$ouName'. The setting was applied but could not be confirmed after $secBlockAttempts attempts."
                                    Context   = @{ Name = $ouName; DistinguishedName = $newOU.DistinguishedName; Attempts = $secBlockAttempts }
                                }
                                Write-Host "    `u{274C} Security Inheritance was not disabled for OU '$ouName' (after $secBlockAttempts attempts)" -ForegroundColor Red
                                Write-TierModelLog -Level Error -Message "OuDisableSecInheritUnverified" -Data @{
                                    OUName = $ouName
                                    DistinguishedName = $newOU.DistinguishedName
                                    Attempts = $secBlockAttempts
                                    Error = $secBlockLastError
                                    CorrelationId = $CorrelationId
                                } | Out-Null
                            }
                        }
                        
                        $applied += [PSCustomObject]@{
                            Name = $ouName
                            DistinguishedName = $newOU.DistinguishedName
                            ObjectGUID = $newOU.ObjectGUID
                            ActionsPerformed = $actionsPerformed
                            Warnings = $warnings
                        }
                        
                        Write-TierModelLog -Level Info -Message "OuCreateSuccess" -Data @{
                            Name = $ouName
                            DistinguishedName = $newOU.DistinguishedName
                            ObjectGuid = $newOU.ObjectGUID
                            ActionsPerformed = $actionsPerformed
                            CorrelationId = $CorrelationId
                        } | Out-Null
                } else {
                    # ShouldProcess returned false - either WhatIf or user declined
                    $reason = if ($WhatIfPreference) { 'WhatIf' } else { 'UserDeclined' }
                    $skipped += [PSCustomObject]@{
                        Name = $ouName
                        Path = $ouPath
                        Reason = $reason
                        ActionsPlanned = @('CreateOU')
                    }
                }
            } catch {
                $errorMsg = "Failed to create OU '$($action.Name)': $($_.Exception.Message)"
                $errors += @{
                    Timestamp = Get-Date
                    Category = 'Execution'
                    Code = 'CreateOuFailed'
                    Message = $errorMsg
                    Context = @{
                        Name = $action.Name
                        Path = $action.Path
                        Exception = $_.Exception.Message
                    }
                }
                
                Write-TierModelLog -Level Error -Message "OuCreateError" -Data @{
                    Name = $action.Name
                    Path = $action.Path
                    ExceptionMessage = $_.Exception.Message
                    CorrelationId = $CorrelationId
                } | Out-Null
            }
        }
        
        $endTime = Get-Date
        $durationMs = [int]($endTime - $startTime).TotalMilliseconds
        $converged = $applied.Count -eq 0
        
        Write-TierModelLog -Level Info -Message "OuCreateComplete" -Data @{
            AppliedCount = $applied.Count
            SkippedCount = $skipped.Count
            ErrorCount = $errors.Count
            DurationMs = $durationMs
            Converged = $converged
            CorrelationId = $CorrelationId
        } | Out-Null
        
        return [PSCustomObject]@{
            Applied = $applied
            Skipped = $skipped
            Errors = $errors
            DurationMs = $durationMs
            Converged = $converged
            CorrelationId = $CorrelationId
        }
        
    } catch {
        $endTime = Get-Date
        $durationMs = [int]($endTime - $startTime).TotalMilliseconds
        
        $errors += @{
            Timestamp = Get-Date
            Category = 'Execution'
            Code = 'OuApplyFailed'
            Message = "OU application failed: $($_.Exception.Message)"
            Context = @{
                Exception = $_.Exception.Message
            }
        }
        
        Write-TierModelLog -Level Error -Message "OU application failed" -Data @{
            Exception = $_.Exception.Message
            DurationMs = $durationMs
            CorrelationId = $CorrelationId
        } | Out-Null
        
        return [PSCustomObject]@{
            Applied = $applied
            Skipped = $skipped
            Errors = $errors
            DurationMs = $durationMs
            Converged = $false
            CorrelationId = $CorrelationId
        }
    }
}