function New-TierModelWinLapsAcl {
    <#
    .SYNOPSIS
    Execute Windows LAPS DACL delegation deployment plan.

    .DESCRIPTION
    Applies Windows LAPS DACL delegations in Active Directory based on the deployment
    plan generated by Get-TierModelWinLapsAcl or Get-TierModelWinLapsAclFd.
    Calls Set-LapsADComputerSelfPermission, Set-LapsADReadPasswordPermission, and
    Set-LapsADResetPasswordPermission for each configured delegation entry.
    All calls include -DomainController for deterministic DC targeting.
    -AllowedPrincipals uses NetBIOS\sAMAccountName format and supports arrays.
    Uses only Windows LAPS (ms-LAPS-*) — never legacy (ms-Mcs-AdmPwd*, AdmPwd.PS).

    .PARAMETER Plan
    Deployment plan object from Get-TierModelWinLapsAcl or Get-TierModelWinLapsAclFd
    containing LAPS permission actions to execute.

    .PARAMETER DomainController
    The domain controller to use for Active Directory operations.

    .PARAMETER Config
    The TierModel configuration object (passed for consistency with other New-TierModel*Acl cmdlets).

    .OUTPUTS
    PSCustomObject with Applied, Skipped, Errors, DurationMs, and Converged status.

    .EXAMPLE
    $plan = Get-TierModelWinLapsAcl -Config $config -DomainController 'DC01'
    New-TierModelWinLapsAcl -Plan $plan -DomainController 'DC01' -Config $config

    .EXAMPLE
    # WhatIf mode — zero AD writes
    New-TierModelWinLapsAcl -Plan $plan -DomainController 'DC01' -Config $config -WhatIf
    #>
    [CmdletBinding(SupportsShouldProcess)]
    param(
        [Parameter(Mandatory)]
        [object]$Plan,

        [Parameter(Mandatory)]
        [string]$DomainController,

        [Parameter(Mandatory)]
        [object]$Config
    )

    $CorrelationId = [System.Guid]::NewGuid().ToString()
    $startTime = Get-Date

    Write-TierModelLog -Level Info -Message "WinLapsAclExecutionStart" -Data @{
        TotalActions      = @($Plan.Actions | Where-Object { $_.Action -eq 'CreateAcl' }).Count
        DomainController  = $DomainController
        WhatIf            = $WhatIfPreference
        CorrelationId     = $CorrelationId
    } | Out-Null

    try {
        $applied = @()
        $skipped = @()
        $errors = @()
        $converged = $true

        foreach ($action in $Plan.Actions) {
            if ($action.Action -eq 'CreateAcl' -and $action.ResourceType -eq 'LapsPermission') {
                try {
                    $lapsOp = $action.Data.lapsOperation
                    $ouDn = $action.Data.ouDn
                    $ouName = if ($ouDn -match '^OU=([^,]+)') { $matches[1] } else { $ouDn }

                    # Resolve principals display for logging
                    $principalDisplay = if ($action.Data.PSObject.Properties['allowedPrincipals']) {
                        ($action.Data.allowedPrincipals -join ', ')
                    } else { 'SELF' }

                    Write-TierModelLog -Level Info -Message "Applying Windows LAPS delegation" -Data @{
                        LapsOperation    = $lapsOp
                        TargetOU         = $ouDn
                        Principals       = $principalDisplay
                        DomainController = $DomainController
                        CorrelationId    = $CorrelationId
                    } | Out-Null

                    $shouldProcessTarget = "OU: $ouDn"
                    $shouldProcessAction = switch ($lapsOp) {
                        'SetComputerSelfPermission'  { "Set-LapsADComputerSelfPermission -DomainController $DomainController" }
                        'SetReadPasswordPermission'  { "Set-LapsADReadPasswordPermission for $principalDisplay -DomainController $DomainController" }
                        'SetResetPasswordPermission' { "Set-LapsADResetPasswordPermission for $principalDisplay -DomainController $DomainController" }
                        default { "Unknown LAPS operation: $lapsOp" }
                    }

                    if ($PSCmdlet.ShouldProcess($shouldProcessTarget, $shouldProcessAction)) {
                        switch ($lapsOp) {
                            'SetComputerSelfPermission' {
                                Set-LapsADComputerSelfPermission -Identity $ouDn -DomainController $DomainController -ErrorAction Stop | Out-Null
                                Write-Host "  `u{2705} Applied LAPS Self-Permission: $ouName" -ForegroundColor Green
                            }
                            'SetReadPasswordPermission' {
                                $principals = @($action.Data.allowedPrincipals)
                                Set-LapsADReadPasswordPermission -Identity $ouDn -AllowedPrincipals $principals -DomainController $DomainController -ErrorAction Stop | Out-Null
                                Write-Host "  `u{2705} Applied LAPS Read-Permission: $principalDisplay on $ouName" -ForegroundColor Green
                            }
                            'SetResetPasswordPermission' {
                                $principals = @($action.Data.allowedPrincipals)
                                Set-LapsADResetPasswordPermission -Identity $ouDn -AllowedPrincipals $principals -DomainController $DomainController -ErrorAction Stop | Out-Null
                                Write-Host "  `u{2705} Applied LAPS Reset-Permission: $principalDisplay on $ouName" -ForegroundColor Green
                            }
                        }

                        Write-TierModelLog -Level Info -Message "Windows LAPS delegation applied successfully" -Data @{
                            LapsOperation    = $lapsOp
                            TargetOU         = $ouDn
                            Principals       = $principalDisplay
                            DomainController = $DomainController
                            CorrelationId    = $CorrelationId
                        } | Out-Null

                        $applied += [PSCustomObject]@{
                            Action        = 'CreateAcl'
                            LapsOperation = $lapsOp
                            TargetOU      = $ouDn
                            Principals    = $principalDisplay
                        }
                    } else {
                        Write-Host "  [WhatIf] Would apply LAPS $lapsOp on $ouName" -ForegroundColor DarkYellow
                        $skipped += [PSCustomObject]@{
                            Action        = 'CreateAcl'
                            LapsOperation = $lapsOp
                            TargetOU      = $ouDn
                            Reason        = if ($WhatIfPreference) { 'WhatIf' } else { 'UserDeclined' }
                        }
                    }
                } catch {
                    Write-TierModelLog -Level Error -Message "Failed to apply Windows LAPS delegation" -Data @{
                        LapsOperation    = $action.Data.lapsOperation
                        TargetOU         = $action.Data.ouDn
                        DomainController = $DomainController
                        Exception        = $_.Exception.Message
                        CorrelationId    = $CorrelationId
                    } | Out-Null

                    Write-Host "  ERROR: Failed to apply LAPS $($action.Data.lapsOperation) on $($action.Data.ouDn) - $($_.Exception.Message)" -ForegroundColor Red
                    $errors += @{
                        Timestamp = Get-Date
                        Category  = 'Execution'
                        Code      = 'LapsPermissionFailed'
                        Message   = $_.Exception.Message
                        Context   = @{
                            Action        = $action.Action
                            LapsOperation = $action.Data.lapsOperation
                            TargetOU      = $action.Data.ouDn
                        }
                    }
                    $converged = $false
                }
            }
        }

        # Execute ConfigureLapsDecryptor actions (set ADPasswordEncryptionPrincipal on LAPS GPOs)
        foreach ($action in $Plan.Actions) {
            if ($action.Action -eq 'ConfigureLapsDecryptor' -and $action.ResourceType -eq 'LapsDecryptor') {
                try {
                    $gpoName = $action.Data.gpoName
                    $decryptorValue = $action.Data.decryptorValue
                    $lapsKey = 'HKLM\Software\Microsoft\Windows\CurrentVersion\Policies\LAPS'

                    Write-TierModelLog -Level Info -Message "Configuring LAPS decryptor" -Data @{
                        GpoName          = $gpoName
                        DecryptorValue   = $decryptorValue
                        DomainController = $DomainController
                        CorrelationId    = $CorrelationId
                    } | Out-Null

                    if ($PSCmdlet.ShouldProcess("GPO: $gpoName", "Set-GPRegistryValue ADPasswordEncryptionPrincipal = $decryptorValue")) {
                        Set-GPRegistryValue -Name $gpoName `
                            -Key $lapsKey `
                            -ValueName 'ADPasswordEncryptionPrincipal' `
                            -Type String `
                            -Value $decryptorValue `
                            -Server $DomainController | Out-Null

                        Write-Host "  `u{2705} Configured LAPS decryptor: $decryptorValue on $gpoName" -ForegroundColor Green

                        Write-TierModelLog -Level Info -Message "LAPS decryptor configured successfully" -Data @{
                            GpoName          = $gpoName
                            DecryptorValue   = $decryptorValue
                            DomainController = $DomainController
                            CorrelationId    = $CorrelationId
                        } | Out-Null

                        $applied += [PSCustomObject]@{
                            Action         = 'ConfigureLapsDecryptor'
                            LapsOperation  = 'SetDecryptorPrincipal'
                            GpoName        = $gpoName
                            DecryptorValue = $decryptorValue
                        }
                    } else {
                        Write-Host "  [WhatIf] Would configure LAPS decryptor: $decryptorValue on $gpoName" -ForegroundColor DarkYellow
                        $skipped += [PSCustomObject]@{
                            Action    = 'ConfigureLapsDecryptor'
                            GpoName   = $gpoName
                            Reason    = if ($WhatIfPreference) { 'WhatIf' } else { 'UserDeclined' }
                        }
                    }
                } catch {
                    Write-TierModelLog -Level Error -Message "Failed to configure LAPS decryptor" -Data @{
                        GpoName        = $action.Data.gpoName
                        DomainController = $DomainController
                        Exception      = $_.Exception.Message
                        CorrelationId  = $CorrelationId
                    } | Out-Null

                    Write-Host "  ERROR: Failed to configure LAPS decryptor on '$($action.Data.gpoName)' - $($_.Exception.Message)" -ForegroundColor Red
                    $errors += @{
                        Timestamp = Get-Date
                        Category  = 'Execution'
                        Code      = 'LapsDecryptorFailed'
                        Message   = $_.Exception.Message
                        Context   = @{
                            Action   = $action.Action
                            GpoName  = $action.Data.gpoName
                        }
                    }
                    $converged = $false
                }
            }
        }

        $durationMs = ((Get-Date) - $startTime).TotalMilliseconds

        Write-TierModelLog -Level Info -Message "WinLapsAclExecutionComplete" -Data @{
            AppliedActions = $applied.Count
            FailedActions  = $errors.Count
            SkippedActions = $skipped.Count
            DurationMs     = $durationMs
            CorrelationId  = $CorrelationId
        } | Out-Null

        return [PSCustomObject]@{
            Applied       = $applied
            Executed      = $applied.Count
            Failed        = $errors.Count
            Skipped       = $skipped
            Errors        = $errors
            DurationMs    = $durationMs
            Converged     = $converged
            CorrelationId = $CorrelationId
        }
    } catch {
        Write-TierModelLog -Level Error -Message "Windows LAPS ACL execution failed" -Data @{ Exception = $_.Exception.Message; CorrelationId = $CorrelationId } | Out-Null
        return [PSCustomObject]@{
            Applied = @(); Executed = 0; Failed = 1; Skipped = @()
            Errors = @(@{ Timestamp = Get-Date; Category = 'Critical'; Code = 'LapsAclExecutionFailed'; Message = $_.Exception.Message; Context = @{ CorrelationId = $CorrelationId } })
            DurationMs = ((Get-Date) - $startTime).TotalMilliseconds; Converged = $false; CorrelationId = $CorrelationId
        }
    }
}
