function New-TierModelGroup {
    <#
    .SYNOPSIS
    Apply group creation plan by creating security groups in Active Directory.
    
    .DESCRIPTION
    Executes group creation actions from a plan generated by Get-TierModelGroup.
    Creates groups using New-ADGroup with specified properties including name,
    SAM account name, path, group scope, category, and description.
    
    .PARAMETER Plan
    Plan object output from Get-TierModelGroup containing Actions array.
    
    .PARAMETER DomainController
    Preferred domain controller for operations.
    
    .OUTPUTS
    PSCustomObject with Applied, Skipped, Errors, DurationMs, and Converged status.
    
    .EXAMPLE
    $config = Get-TierModelConfig
    $plan = Get-TierModelGroup -Config $config -DomainController "DC01.contoso.com"
    $result = New-TierModelGroup -Plan $plan -DomainController "DC01.contoso.com"
    
    .EXAMPLE
    $result = New-TierModelGroup -Plan $plan -DomainController "DC01.contoso.com" -WhatIf
    #>
    [CmdletBinding(SupportsShouldProcess)]
    param(
        [Parameter(Mandatory)]
        [object]$Plan,
        
        [Parameter(Mandatory)]
        [string]$DomainController
    )
    
    $CorrelationId = $script:CorrelationId
    $startTime = Get-Date
    
    Write-TierModelLog -Level Info -Message "GroupCreateStart" -Data @{
        CorrelationId = $CorrelationId
        DomainController = $DomainController
        WhatIf = $WhatIfPreference
        PlanActionCount = @($Plan.Actions | Where-Object { $_.Action -eq 'CreateGroup' }).Count
    } | Out-Null
    
    $applied = @()
    $skipped = @()
    $errors = @()
    
    try {
        # Process only CreateGroup actions from the plan
        $createActions = $Plan.Actions | Where-Object { $_.Action -eq 'CreateGroup' }
        
        if ($createActions.Count -eq 0) {
            Write-TierModelLog -Level Info -Message "No group creation actions in plan" -Data @{
                CorrelationId = $CorrelationId
            } | Out-Null
        }
        
        foreach ($action in $createActions) {
            try {
                $groupData = $action.Data
                $groupName = $groupData.name
                $groupSamAccountName = $groupData.samaccountname
                $groupPath = $action.Path
                
                # Get description safely
                $groupDescription = if ($groupData.PSObject.Properties.Name -contains 'description') { 
                    $groupData.description 
                } elseif ($groupData.PSObject.Properties.Name -contains 'comment') { 
                    $groupData.comment 
                } else { 
                    $null 
                }
                
                # Get group scope and category with defaults
                $groupScope = if ($groupData.PSObject.Properties.Name -contains 'groupscope') { 
                    $groupData.groupscope 
                } else { 
                    'Global' 
                }
                $groupCategory = if ($groupData.PSObject.Properties.Name -contains 'groupcategory') { 
                    $groupData.groupcategory 
                } else { 
                    'Security' 
                }
                
                Write-TierModelLog -Level Info -Message "GroupCreateStart" -Data @{
                    Name = $groupName
                    SamAccountName = $groupSamAccountName
                    Path = $groupPath
                    GroupScope = $groupScope
                    GroupCategory = $groupCategory
                    WhatIf = $WhatIfPreference
                    CorrelationId = $CorrelationId
                } | Out-Null
                
                if ($PSCmdlet.ShouldProcess("Group: $groupName", "Create security group at $groupPath")) {
                    if ($WhatIfPreference) {
                        # WhatIf mode - add to skipped with reason
                        $skipped += [PSCustomObject]@{
                            Name = $groupName
                            SamAccountName = $groupSamAccountName
                            Path = $groupPath
                            Reason = 'WhatIf'
                            ActionsPlanned = @('CreateGroup')
                        }
                        
                        Write-TierModelLog -Level Info -Message "Group creation skipped (WhatIf)" -Data @{
                            Name = $groupName
                            SamAccountName = $groupSamAccountName
                            Path = $groupPath
                            CorrelationId = $CorrelationId
                        } | Out-Null
                    } else {
                        # Show creation progress
                        Write-Host "  ✅ Creating Group: $groupName ($groupSamAccountName)" -ForegroundColor Green
                        
                        # Create the Group using New-ADGroup
                        $newGroupParams = @{
                            Name = $groupName
                            SamAccountName = $groupSamAccountName
                            Path = $groupPath
                            GroupScope = $groupScope
                            GroupCategory = $groupCategory
                            Server = $DomainController
                            Confirm = $false
                        }
                        
                        # Add optional properties if they exist
                        if ($groupDescription) {
                            $newGroupParams['Description'] = $groupDescription
                        }
                        
                        $newGroup = New-ADGroup @newGroupParams -PassThru
                        
                        $applied += [PSCustomObject]@{
                            Name = $groupName
                            SamAccountName = $groupSamAccountName
                            DistinguishedName = $newGroup.DistinguishedName
                            ObjectGUID = $newGroup.ObjectGUID
                            GroupScope = $newGroup.GroupScope
                            GroupCategory = $newGroup.GroupCategory
                            ActionsPerformed = @('CreateGroup')
                        }
                        
                        Write-TierModelLog -Level Info -Message "GroupCreateSuccess" -Data @{
                            Name = $groupName
                            SamAccountName = $groupSamAccountName
                            DistinguishedName = $newGroup.DistinguishedName
                            ObjectGuid = $newGroup.ObjectGUID
                            GroupScope = $newGroup.GroupScope
                            GroupCategory = $newGroup.GroupCategory
                            CorrelationId = $CorrelationId
                        } | Out-Null
                    }
                } else {
                    # User declined ShouldProcess
                    $skipped += [PSCustomObject]@{
                        Name = $groupName
                        SamAccountName = $groupSamAccountName
                        Path = $groupPath
                        Reason = 'UserDeclined'
                        ActionsPlanned = @('CreateGroup')
                    }
                }
            } catch {
                $errorMsg = "Failed to create group '$($action.Name)': $($_.Exception.Message)"
                $errors += @{
                    Timestamp = Get-Date
                    Category = 'Execution'
                    Code = 'CreateGroupFailed'
                    Message = $errorMsg
                    Context = @{
                        Name = $action.Name
                        SamAccountName = $action.Data.samaccountname
                        Path = $action.Path
                        Exception = $_.Exception.Message
                    }
                }
                
                Write-TierModelLog -Level Error -Message "GroupCreateError" -Data @{
                    Name = $action.Name
                    SamAccountName = $action.Data.samaccountname
                    Path = $action.Path
                    ExceptionMessage = $_.Exception.Message
                    CorrelationId = $CorrelationId
                } | Out-Null
            }
        }
        
        $endTime = Get-Date
        $durationMs = [int]($endTime - $startTime).TotalMilliseconds
        $converged = $applied.Count -eq 0
        
        Write-TierModelLog -Level Info -Message "GroupCreateComplete" -Data @{
            AppliedCount = $applied.Count
            SkippedCount = $skipped.Count
            ErrorCount = $errors.Count
            DurationMs = $durationMs
            Converged = $converged
            CorrelationId = $CorrelationId
        } | Out-Null
        
        return [PSCustomObject]@{
            Applied = $applied
            Skipped = $skipped
            Errors = $errors
            DurationMs = $durationMs
            Converged = $converged
            CorrelationId = $CorrelationId
        }
        
    } catch {
        $endTime = Get-Date
        $durationMs = [int]($endTime - $startTime).TotalMilliseconds
        
        $errors += @{
            Timestamp = Get-Date
            Category = 'Execution'
            Code = 'GroupApplyFailed'
            Message = "Group application failed: $($_.Exception.Message)"
            Context = @{
                Exception = $_.Exception.Message
            }
        }
        
        Write-TierModelLog -Level Error -Message "Group application failed" -Data @{
            Exception = $_.Exception.Message
            DurationMs = $durationMs
            CorrelationId = $CorrelationId
        } | Out-Null
        
        return [PSCustomObject]@{
            Applied = $applied
            Skipped = $skipped
            Errors = $errors
            DurationMs = $durationMs
            Converged = $false
            CorrelationId = $CorrelationId
        }
    }
}