function Update-TierModelGPOConfig {
    <#
    .SYNOPSIS
    Execute TierModel GPO configuration from deployment plan.
    
    .DESCRIPTION
    Updates GPO security template configuration (GptTmpl.inf) based on the deployment plan
    generated by Get-TierModelGpo. Handles GptTmpl.inf generation and validation for
    PostConfigureGpo workflow requirements.
    
    .PARAMETER Plan
    Deployment plan object from Get-TierModelGpo containing GPO configuration actions to execute.
    
    .PARAMETER DomainController
    The domain controller to use for Active Directory operations.
    
    .EXAMPLE
    $plan = Get-TierModelGpo -Config $gpoConfig -DomainController "DC01"
    Update-TierModelGPOConfig -Plan $plan -DomainController "DC01"
    
    .OUTPUTS
    PSCustomObject with execution results including success/failure counts and details.
    #>
    [CmdletBinding(SupportsShouldProcess)]
    param(
        [Parameter(Mandatory)]
        [object]$Plan,
        
        [Parameter(Mandatory)]
        [string]$DomainController,
        
        [string]$MockFilePath
    )
    
    $CorrelationId = [System.Guid]::NewGuid().ToString()
    $startTime = Get-Date
    
    # Filter to only ConfigureGPO actions
    $configActions = @($Plan.Actions | Where-Object { $_.Action -eq 'ConfigureGPO' })
    
    Write-TierModelLog -Level Info -Message "GPO configuration start" -Data @{
        TotalActions = $configActions.Count
        DomainController = $DomainController
        WhatIf = $PSCmdlet.ShouldProcess
        CorrelationId = $CorrelationId
    } | Out-Null
    
    try {
        $executed = 0
        $failed = 0
        $skipped = 0
        $errors = @()
        $converged = $true
        
        foreach ($action in $configActions) {
            try {
                $gpoData = $action.Data
                $gpoName = $gpoData.name
                $targetOUPath = $action.Path
                
                Write-TierModelLog -Level Info -Message "Configuring GPO" -Data @{
                    Name = $gpoName
                    TargetOU = $targetOUPath
                }
                
                # GPO configuration starts (removed verbose message)
                
                if ($PSCmdlet.ShouldProcess("GPO: $gpoName", "Configure GPO")) {
                    
                    # Get the GPO object to determine SYSVOL path
                    $gpo = Get-GPO -Name $gpoName -Server $DomainController
                    if (-not $gpo) {
                        throw "GPO '$gpoName' not found"
                    }
                    
                    # Get domain information for SYSVOL path construction
                    $domain = Get-ADDomain -Server $DomainController
                    $domainName = $domain.DNSRoot
                    $domainController = $domain.PDCEmulator  # Use PDC for SYSVOL operations
                    
                    # Build SYSVOL path to GPO's Machine folder
                    $gpoSysvolPath = "\\$domainController\SYSVOL\$domainName\Policies\{$($gpo.Id)}\Machine"
                    
                    # SYSVOL path: $gpoSysvolPath (removed verbose message)
                    
                    # Ensure the Machine folder exists
                    if (-not (Test-Path -Path $gpoSysvolPath)) {
                        Write-Host "    Creating Machine folder..." -ForegroundColor Cyan
                        New-Item -Path $gpoSysvolPath -ItemType Directory -Force | Out-Null
                    }
                    
                    # Build path to GptTmpl.inf
                    $gptTmplPath = Join-Path $gpoSysvolPath "Microsoft\Windows NT\SecEdit\GptTmpl.inf"
                    
                    # Ensure the SecEdit folder exists
                    $secEditFolder = Split-Path $gptTmplPath -Parent
                    if (-not (Test-Path -Path $secEditFolder)) {
                        Write-Host "    Creating SecEdit folder structure..." -ForegroundColor Cyan
                        New-Item -Path $secEditFolder -ItemType Directory -Force | Out-Null
                    }
                    
                    # Generate GptTmpl.inf content using standardized function
                    # Generating GptTmpl.inf content... (removed verbose message)
                    
                    $gptTmplContent = New-TierModelGptTmplContent -GPOData $gpoData -DomainController $DomainController -StrictMode
                    
                    # Write mock file for debugging if specified
                    if ($MockFilePath) {
                        $gptTmplContent | Out-File -FilePath $MockFilePath -Encoding Unicode -Force
                        Write-Host "    Mock GptTmpl.inf saved to: $MockFilePath" -ForegroundColor Yellow
                    }
                    
                    # Write GptTmpl.inf file with proper encoding
                    # Use UTF-16LE encoding for Windows INF files
                    $gptTmplContent | Out-File -FilePath $gptTmplPath -Encoding Unicode -Force
                    
                    # Validate the file was created successfully
                    if (Test-Path -Path $gptTmplPath) {
                        $fileInfo = Get-Item -Path $gptTmplPath
                        
                        Write-TierModelLog -Level Info -Message "GPO configuration completed" -Data @{
                            GPOName = $gpoName
                            GptTmplPath = $gptTmplPath
                            FileSize = $fileInfo.Length
                            CorrelationId = $CorrelationId
                        } | Out-Null
                        
                        Write-Host "  ✅ Configured GPO: $gpoName" -ForegroundColor Green
                        $executed++
                        
                    } else {
                        throw "Failed to create GptTmpl.inf file at: $gptTmplPath"
                    }
                    
                } else {
                    Write-Host "  [WhatIf] Would configure GPO: $gpoName" -ForegroundColor DarkYellow
                    $skipped++
                }
                
            } catch {
                Write-TierModelLog -Level Error -Message "Failed to configure GPO" -Data @{
                    GPOName = $action.Data.name
                    Exception = $_.Exception.Message
                    CorrelationId = $CorrelationId
                } | Out-Null
                
                Write-Host "  ERROR: Failed to configure GPO '$($action.Data.name)' - $($_.Exception.Message)" -ForegroundColor Red
                $errors += @{
                    Timestamp = Get-Date
                    Category = 'Execution'
                    Code = 'GPOConfigurationFailed'
                    Message = $_.Exception.Message
                    Context = @{
                        Action = $action.Action
                        GPOName = $action.Data.name
                    }
                }
                $failed++
                $converged = $false
            }
        }
        
        $durationMs = ((Get-Date) - $startTime).TotalMilliseconds
        
        Write-TierModelLog -Level Info -Message "GPO configuration complete" -Data @{
            ExecutedActions = $executed
            FailedActions = $failed
            SkippedActions = $skipped
            DurationMs = $durationMs
            CorrelationId = $CorrelationId
        } | Out-Null
        
        return [PSCustomObject]@{
            Executed = $executed
            Failed = $failed
            Skipped = $skipped
            Errors = $errors
            DurationMs = $durationMs
            Converged = $converged
            CorrelationId = $CorrelationId
        }
        
    } catch {
        Write-TierModelLog -Level Error -Message "GPO configuration failed" -Data @{
            Exception = $_.Exception.Message
            CorrelationId = $CorrelationId
        } | Out-Null
        
        return [PSCustomObject]@{
            Executed = 0
            Failed = 1
            Skipped = 0
            Errors = @(@{
                Timestamp = Get-Date
                Category = 'Critical'
                Code = 'GPOConfigurationFailed'
                Message = $_.Exception.Message
                Context = @{ CorrelationId = $CorrelationId }
            })
            DurationMs = ((Get-Date) - $startTime).TotalMilliseconds
            Converged = $false
            CorrelationId = $CorrelationId
        }
    }
}